In [1]:
import numpy as np

In [2]:
# Generate a large 1D NumPy array with random integers
large_array = np.random.randint(1, 1000, size=1000000)

# Function to calculate cumulative sum using a for loop
def cumulative_sum_with_loop(arr):
    cum_sum = np.empty_like(arr)
    cum_sum[0] = arr[0]
    for i in range(1, len(arr)):
        cum_sum[i] = cum_sum[i - 1] + arr[i]
    return cum_sum

# Calculate cumulative sum using the for loop method
cumsum_with_loop = cumulative_sum_with_loop(large_array)

# Calculate cumulative sum using NumPy's cumsum() function
cumsum_with_numpy = np.cumsum(large_array)

# Display first 10 results to verify
print("First 10 results using for loop:")
print(cumsum_with_loop[:10])

print("First 10 results using NumPy:")
print(cumsum_with_numpy[:10])

First 10 results using for loop:
[ 685 1554 2036 2494 3457 3458 4404 5146 5919 6840]
First 10 results using NumPy:
[ 685 1554 2036 2494 3457 3458 4404 5146 5919 6840]


In [3]:
# Generate a large 1D NumPy array with random integers
large_array = np.random.randint(1, 1000000, size=1000000)

# Function to find the indices of the maximum element using a for loop
def find_max_index_with_loop(arr):
    max_index = 0
    max_value = arr[0]
    for i in range(1, len(arr)):
        if arr[i] > max_value:
            max_value = arr[i]
            max_index = i
    return max_index

# Find the index of the maximum element using the for loop method
max_index_with_loop = find_max_index_with_loop(large_array)

# Find the index of the maximum element using NumPy's argmax() function
max_index_with_numpy = np.argmax(large_array)

# Display the results
print(f"Index of maximum element using for loop: {max_index_with_loop}")
print(f"Index of maximum element using NumPy: {max_index_with_numpy}")

Index of maximum element using for loop: 114432
Index of maximum element using NumPy: 114432


In [4]:
# Generate a large 1D NumPy array with random integers
large_array = np.random.randint(1, 1000, size=1000000)

# Function to normalize the array using a for loop
def normalize_with_loop(arr):
    mean = np.mean(arr)
    std = np.std(arr)
    normalized_array = np.empty_like(arr, dtype=float)
    for i in range(len(arr)):
        normalized_array[i] = (arr[i] - mean) / std
    return normalized_array

# Normalize the array using the for loop method
normalized_with_loop = normalize_with_loop(large_array)

# Normalize the array using NumPy's vectorized operations
normalized_with_numpy = (large_array - np.mean(large_array)) / np.std(large_array)

# Display first 10 results to verify
print("First 10 normalized values using for loop:")
print(normalized_with_loop[:10])

print("First 10 normalized values using NumPy:")
print(normalized_with_numpy[:10])

First 10 normalized values using for loop:
[ 0.1577963  -1.57277149 -1.07683723 -1.2398366  -1.29185768 -0.98666737
  0.95198472 -1.48953777  1.0040058   0.93811244]
First 10 normalized values using NumPy:
[ 0.1577963  -1.57277149 -1.07683723 -1.2398366  -1.29185768 -0.98666737
  0.95198472 -1.48953777  1.0040058   0.93811244]


In [5]:
# Generate a large 2D NumPy array with random integers
large_2d_array = np.random.randint(1, 1000, size=(1000, 1000))

# Function to compute column-wise mean using a for loop
def column_wise_mean_with_loop(arr):
    num_rows, num_cols = arr.shape
    col_means = np.empty(num_cols)
    for col in range(num_cols):
        col_sum = 0
        for row in range(num_rows):
            col_sum += arr[row, col]
        col_means[col] = col_sum / num_rows
    return col_means

# Compute column-wise mean using the for loop method
col_mean_with_loop = column_wise_mean_with_loop(large_2d_array)

# Compute column-wise mean using NumPy's built-in functions
col_mean_with_numpy = np.mean(large_2d_array, axis=0)

# Display first 10 column means to verify
print("First 10 column means using for loop:")
print(col_mean_with_loop[:10])

print("First 10 column means using NumPy:")
print(col_mean_with_numpy[:10])

First 10 column means using for loop:
[504.079 502.817 480.389 493.772 493.297 498.947 505.977 507.731 506.127
 511.789]
First 10 column means using NumPy:
[504.079 502.817 480.389 493.772 493.297 498.947 505.977 507.731 506.127
 511.789]


In [6]:
# Generate a large 1D NumPy array with random integers
large_array = np.random.randint(1, 10000, size=10000)

# Function to sort the array using a for loop (bubble sort for simplicity)
def sort_with_loop(arr):
    arr_copy = arr.copy()
    n = len(arr_copy)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr_copy[j] > arr_copy[j+1]:
                arr_copy[j], arr_copy[j+1] = arr_copy[j+1], arr_copy[j]
    return arr_copy

# Sort the array using the for loop method
sorted_with_loop = sort_with_loop(large_array)

# Sort the array using NumPy's built-in sort() function
sorted_with_numpy = np.sort(large_array)

# Display first 10 sorted elements to verify
print("First 10 sorted elements using for loop:")
print(sorted_with_loop[:10])

print("First 10 sorted elements using NumPy:")
print(sorted_with_numpy[:10])

First 10 sorted elements using for loop:
[ 2  5  5  5  6  7  8  8 10 11]
First 10 sorted elements using NumPy:
[ 2  5  5  5  6  7  8  8 10 11]
