# NumPy Basic 

In [1]:
import numpy as np

In [3]:
np.__version__

'1.20.3'

In [4]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/singh/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/singh/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/singh/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/singh/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/singh/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/singh/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/singh/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/singh/anaconda3\\Library\\include']


In [5]:
#Q2
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
#Q3 Are all the elements non-zeros?
x = np.array([1,2,3,4])
np.all(x)

True

In [7]:
y = np.array([0,1,2])
np.all(y)

False

In [8]:
#Q4 Is there any False boolean?
np.any(y)

True

In [9]:
z = np.array([0,0,0,0])
np.any(z)

False

In [11]:
#Q5 Is the element finite
a = np.array([1,0, np.nan, np.inf])
np.isfinite(a)

array([ True,  True, False, False])

In [13]:
#Q6 Is the element +/- infinity?
np.isinf(a)

array([False, False, False,  True])

In [14]:
#Q7 is the element NaN?
np.isnan(a)

array([False, False,  True, False])

In [17]:
#Q8 
x = np.array([1+2j, 3+0j, 2.1, 4.7, 2, 8j])
np.iscomplex(x)

array([ True, False, False, False, False,  True])

In [18]:
np.isreal(x)

array([False,  True,  True,  True,  True, False])

In [20]:
np.isscalar(2.2) #checking an element is a scalar or not?

True

In [21]:
np.isscalar([1.2]) #list is not scalar

False

In [22]:
#Q9

print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))

True
False


In [23]:
np.allclose([1e10,1e-7], [1.00001e10,1e-8])

False

In [24]:
np.allclose([1.0, np.nan], [1.0, np.nan])

False

In [25]:
np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)

True

In [33]:
#Q10
x = np.array([4, 5])
y = np.array([2,5])

In [34]:
x

array([4, 5])

In [35]:
y

array([2, 5])

In [36]:
np.greater(x,y)

array([ True, False])

In [37]:
np.greater_equal(x,y)

array([ True,  True])

In [38]:
np.less(x,y)

array([False, False])

In [39]:
np.less(y,x)

array([ True, False])

In [40]:
np.less_equal(x,y)

array([False,  True])