In [1]:
import numpy as np

In [2]:
x = np.random.random((5,3))
x

array([[0.80868162, 0.75769073, 0.9001033 ],
       [0.38888368, 0.88285114, 0.84151017],
       [0.39237703, 0.15904459, 0.51388643],
       [0.53750758, 0.65321338, 0.66583129],
       [0.66137323, 0.26118854, 0.25297473]])

In [3]:
y = np.random.random((3,2))
y

array([[0.54840506, 0.96140116],
       [0.87579271, 0.35745258],
       [0.08295303, 0.13304961]])

In [4]:
z = np.dot(x,y)
z

array([[1.1817314 , 1.16806436],
       [1.05626619, 0.80141324],
       [0.39710008, 0.50245502],
       [0.92208411, 0.83884182],
       [0.61243246, 0.7628657 ]])

In [5]:
x = np.array([1+2j, 3+4j])
x

array([1.+2.j, 3.+4.j])

In [6]:
y =np.array([5+6j, 7+8j])
y

array([5.+6.j, 7.+8.j])

In [8]:
# Calculatin the vector dot product of the two arrays:
z = np.dot(x, y)
z

(-18+68j)

In [9]:
x = np.arange(24).reshape((2, 3, 4))
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [10]:
y = np.arange(4)
y

array([0, 1, 2, 3])

In [11]:
np.inner(x, y)

array([[ 14,  38,  62],
       [ 86, 110, 134]])

In [12]:
x = np.array([1, 4, 0], float)
y = np.array([2, 2, 1], float)
print(x)
print(y)

[1. 4. 0.]
[2. 2. 1.]


In [13]:
# Inner product
np.inner(x, y )

10.0

In [14]:
# Outer product
np.outer(x, y)

array([[2., 2., 1.],
       [8., 8., 4.],
       [0., 0., 0.]])

In [15]:
# Cross product
np.cross(x, y)

array([ 4., -1., -6.])

In [16]:
x = [[1, 0], [1,1]]
y = [[3,1], [2,2]]
print(x)
print(y)

[[1, 0], [1, 1]]
[[3, 1], [2, 2]]


In [17]:
np.matmul(x, y)

array([[3, 1],
       [5, 3]])

In [18]:
np.dot(x, y)

array([[3, 1],
       [5, 3]])

In [21]:
np.roots([1, -4, 7])

array([2.+1.73205081j, 2.-1.73205081j])

In [22]:
np.roots([1, -11, 9, 11, -10])

array([10.        , -1.        ,  0.99999998,  1.00000002])

In [23]:
np.polyval([1, -2, 1], 2)

1

In [24]:
np.polyval([1, -12, 10, 7, -10], 3)

-142

In [25]:
# Importing the required polynomial functions from numpy
from numpy.polynomial import polynomial as P
x = (10, 20, 30)
y = (30, 40, 50)

P. polyadd(x, y)

array([40., 60., 80.])

In [26]:
P.polysub(x, y)

array([-20., -20., -20.])

In [27]:
P.polymul(x, y)

array([ 300., 1000., 2200., 2200., 1500.])

In [28]:
P.polydiv(x, y)

(array([0.6]), array([-8., -4.]))

In [29]:
a = np.array([[10, 30], [20, 60]])
a

array([[10, 30],
       [20, 60]])

In [30]:
# axis 0 (column wise)
a.mean(axis=0)

array([15., 45.])

In [32]:
# axis 1 (row wise)
a.mean(axis=1)

array([20., 40.])

In [33]:
x = np.random.randn(1000)
mean = x.mean()

In [34]:
mean

-0.0006711847172214203

In [35]:
std = x.std()
std

1.0256011023378115

In [36]:
var = x.var()
var

1.051857621116534

In [37]:
# Computing the sine values for an array of angles given in degrees
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

# Computing the cosine values for an array of angles given in degrees
print("cosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

# Computing the tangent values for an array of angles given in degrees
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [38]:
# Creating an array of values (-1, 0, 1)
x = np.array([-1., 0, 1.])

# Computing the inverse sine for each element in the array
print("Inverse sine:", np.arcsin(x))

# Computing the inverse cosine for each element in the array
print("Inverse cosine:", np.arccos(x))

# Computing the inverse tangent for each element in the array
print("Inverse tangent:", np.arctan(x)) 


Inverse sine: [-1.57079633  0.          1.57079633]
Inverse cosine: [3.14159265 1.57079633 0.        ]
Inverse tangent: [-0.78539816  0.          0.78539816]


In [39]:
# Creating an array of angles in radians: [-π, -π/2, π/2, π]
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

# Converting angles from radians to degrees using np.degrees()
r1 = np.degrees(x)

# Converting angles from radians to degrees using np.rad2deg()
r2 = np.rad2deg(x)

# Checking if the results from np.degrees() and np.rad2deg() are equivalent
assert np.array_equiv(r1, r2)

# Printing the converted angles in degrees
print(r1) 

[-180.  -90.   90.  180.]


In [40]:
# Creating an array of angles in degrees: [-180, -90, 90, 180]
x = np.array([-180., -90., 90., 180.])

# Converting angles from degrees to radians using np.radians()
r1 = np.radians(x)

# Converting angles from degrees to radians using np.deg2rad()
r2 = np.deg2rad(x)

# Checking if the results from np.radians() and np.deg2rad() are equivalent
assert np.array_equiv(r1, r2)

# Printing the converted angles in radians
print(r1) 

[-3.14159265 -1.57079633  1.57079633  3.14159265]


In [41]:
x = np.array([-1, 0, 1])

In [42]:
np.sinh(x)

array([-1.17520119,  0.        ,  1.17520119])

In [43]:
np.cosh(x)

array([1.54308063, 1.        , 1.54308063])

In [44]:
np.tanh(x)

array([-0.76159416,  0.        ,  0.76159416])

Q26 onwards