In [3]:
# Importing the necessary NumPy library
import numpy as np

# Create a 4x4 array with random values
array = np.random.rand(4, 4)

# Extract the lower triangular part of the matrix
lower_triangular = np.tril(array)

# Printing the original array and its lower triangular part
print("4x4 Array:\n", array)
print("Lower Triangular Part of the Array:\n", lower_triangular)


4x4 Array:
 [[0.37661607 0.65082002 0.51335036 0.08388906]
 [0.538288   0.03538499 0.96142442 0.72191792]
 [0.33314527 0.44230732 0.58458579 0.05425012]
 [0.41694462 0.17589933 0.94634224 0.25129132]]
Lower Triangular Part of the Array:
 [[0.37661607 0.         0.         0.        ]
 [0.538288   0.03538499 0.         0.        ]
 [0.33314527 0.44230732 0.58458579 0.        ]
 [0.41694462 0.17589933 0.94634224 0.25129132]]


In [4]:
# Create a 6x6 array with random values
array = np.random.rand(6, 6)

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(array)
"""The rank of a matrix is the maximum number of linearly independent
row or column vectors in the matrix."""

# Printing the original array and its rank
print("6x6 Array:\n", array)
print("Rank of the array:\n", rank)

6x6 Array:
 [[0.46178053 0.99593209 0.5813682  0.71874916 0.50258411 0.94629809]
 [0.51673859 0.99074758 0.5260923  0.69423014 0.49567103 0.21348414]
 [0.77662892 0.72822022 0.90607902 0.9789338  0.31894915 0.80687424]
 [0.34416612 0.57620517 0.10046543 0.44426497 0.19053911 0.07154814]
 [0.74011076 0.04528928 0.94214075 0.70128194 0.04520755 0.51906232]
 [0.87224819 0.54477902 0.95364972 0.94560826 0.52737741 0.01621188]]
Rank of the array:
 6


In [11]:
# Create a 3x3 array with random values 
array = np.random.rand(3, 3)

# Compute the Frobenius norm  of the matrix
frobenius_norm = np.linalg.norm(array, 'fro')

"""The np.linalg.norm function with the 'fro' argument 
calculates the Frobenius norm of the matrix, which is 
the square root of the sum of the absolute squares of its elements."""

# Printing the original array and its Frobenious norm
print("3x3 Array:\n", array)
print("Frobenius Norm of the Array:\n", frobenius_norm)

3x3 Array:
 [[0.73437574 0.01957449 0.09529108]
 [0.21946889 0.08750564 0.58340443]
 [0.11732704 0.11819262 0.1624732 ]]
Frobenius Norm of the Array:
 0.9995441486218067


In [12]:
# Create a 5x5 array with random values
array = np.random.random((5, 5))

# Find the index of the maximum value in each row
max_indices = np.argmax(array, axis=1)

# Print the array and the indices of the maximum values
print("Array:\n", array)
print("Indices of the maximum values in each row:\n", max_indices)

Array:
 [[0.34901276 0.0881017  0.15690847 0.54505974 0.98561037]
 [0.16640151 0.18469401 0.93005695 0.59281081 0.3791498 ]
 [0.02146969 0.54805519 0.87241845 0.67216509 0.16112685]
 [0.1997184  0.86296206 0.30198091 0.29746468 0.29254171]
 [0.77684598 0.92733579 0.37270635 0.47852455 0.2145958 ]]
Indices of the maximum values in each row:
 [4 2 2 1 1]


In [13]:
# Create a 5x5 array with random values
array = np.random.random((5, 5))

# Find the index of the minimum value in each row
min_indices = np.argmin(array, axis=1)

# Print the array and the indices of the minimum values
print("Array:\n", array)
print("Indices of the minimum values in each row:\n", min_indices)

Array:
 [[0.48574733 0.31874751 0.69544464 0.35296767 0.21973948]
 [0.60280148 0.10539654 0.5167748  0.72965642 0.13232707]
 [0.86114031 0.58583922 0.0110095  0.95612323 0.31287424]
 [0.25328108 0.2037672  0.22381827 0.1471863  0.01789432]
 [0.45274767 0.56099818 0.59232517 0.30144376 0.07446205]]
Indices of the minimum values in each row:
 [4 1 2 4 4]


In [14]:
# Create a 3x3 array with random values
array = np.random.random((3, 3))

# Compute the QR decomposition
q, r = np.linalg.qr(array)

"""QR decomposition is a factorization of a matrix 
into an orthogonal matrix 𝑄 and an upper triangular matrix 𝑅. 
In NumPy, the numpy.linalg.qr() function computes
the QR decomposition of a given matrix.
It's often used in numerical linear algebra for 
solving linear least squares problems, eigenvalue problems,
and many other applications."""

# Print the original array, Q matrix, and R matrix
print("Original Array:\n", array)
print("Q Matrix:\n", q)
print("R Matrix:\n", r)

Original Array:
 [[0.25170197 0.49641558 0.3404579 ]
 [0.57780421 0.29636675 0.73360933]
 [0.34110628 0.71606286 0.39853045]]
Q Matrix:
 [[-0.35122779  0.43892155 -0.82703501]
 [-0.80627457 -0.59083786  0.02884348]
 [-0.47598357  0.67694793  0.56140996]]
R Matrix:
 [[-0.71663455 -0.75414208 -0.90076277]
 [ 0.          0.52752007 -0.01422549]
 [ 0.          0.         -0.03667179]]


In [15]:
# Create a 3x3 array with random values
array = np.random.random((3, 3))

# Make the array symmetric and positive-definite for Cholesky decomposition
symmetric_array = np.dot(array, array.T)

# Compute the Cholesky decomposition
cholesky_decomp = np.linalg.cholesky(symmetric_array)

# Print the original array, symmetric array, and Cholesky decomposition
print("Original Array:\n", array)
print("Symmetric Positive-Definite Array:\n", symmetric_array)
print("Cholesky Decomposition:\n", cholesky_decomp)

Original Array:
 [[0.8934658  0.20001898 0.23693548]
 [0.78735102 0.26545306 0.45942066]
 [0.13383587 0.38351693 0.40550124]]
Symmetric Positive-Definite Array:
 [[0.89442716 0.86541992 0.29236607]
 [0.86541992 0.9014543  0.3934772 ]
 [0.29236607 0.3934772  0.32942853]]
Cholesky Decomposition:
 [[0.94574159 0.         0.        ]
 [0.91507017 0.25318152 0.        ]
 [0.30913949 0.43681258 0.20749958]]


In [16]:
# Create a 4x4 array with random values
array = np.random.random((4, 4))

# Print the original array
print("Original Array:\n", array)

# Swap the first and last rows
array[[0, -1]] = array[[-1, 0]]

# Print the array after swapping the first and last rows
print("Array after swapping first and last rows:\n", array)

Original Array:
 [[0.35723061 0.75534537 0.57827546 0.68733982]
 [0.13508997 0.63720936 0.48790152 0.905937  ]
 [0.5052132  0.64729575 0.38828838 0.02303195]
 [0.6664016  0.51453569 0.88698317 0.67155919]]
Array after swapping first and last rows:
 [[0.6664016  0.51453569 0.88698317 0.67155919]
 [0.13508997 0.63720936 0.48790152 0.905937  ]
 [0.5052132  0.64729575 0.38828838 0.02303195]
 [0.35723061 0.75534537 0.57827546 0.68733982]]


In [17]:
# Create a 4x4 array with random values
array = np.random.random((4, 4))

# Print the original array
print("Original Array:\n", array)

# Rotate the array 90 degrees counterclockwise
rotated_array = np.rot90(array)

# Print the rotated array
print("Array after 90 degrees counterclockwise rotation:\n", rotated_array)

Original Array:
 [[0.61543911 0.42220964 0.63031007 0.18971788]
 [0.78884606 0.89233605 0.01373433 0.2606718 ]
 [0.75200904 0.56385187 0.2702985  0.39410384]
 [0.67434357 0.3468061  0.54364731 0.43846729]]
Array after 90 degrees counterclockwise rotation:
 [[0.18971788 0.2606718  0.39410384 0.43846729]
 [0.63031007 0.01373433 0.2702985  0.54364731]
 [0.42220964 0.89233605 0.56385187 0.3468061 ]
 [0.61543911 0.78884606 0.75200904 0.67434357]]


In [18]:
# Create a 4x4 array with random values
array = np.random.random((4, 4))

# Print the original array
print("Original Array:\n", array)

# Shift all elements one position to the right
shifted_array = np.roll(array, shift=1, axis=1)

# Print the shifted array
print("Array after shifting all elements one position to the right:\n", shifted_array)

Original Array:
 [[0.10111646 0.31095929 0.75546759 0.67613617]
 [0.63193071 0.27264266 0.44903935 0.07404246]
 [0.17632988 0.18566931 0.45754795 0.93153083]
 [0.36400002 0.60226462 0.05690359 0.87470433]]
Array after shifting all elements one position to the right:
 [[0.67613617 0.10111646 0.31095929 0.75546759]
 [0.07404246 0.63193071 0.27264266 0.44903935]
 [0.93153083 0.17632988 0.18566931 0.45754795]
 [0.87470433 0.36400002 0.60226462 0.05690359]]


In [19]:
# Create a 4x4 array with random values
array = np.random.random((4, 4))

# Print the original array
print("Original Array:\n", array)

# Shift all elements one position downwards
shifted_array = np.roll(array, shift=1, axis=0)

# Print the shifted array
print("Array after shifting all elements one position downwards:\n", shifted_array)

Original Array:
 [[0.83756018 0.93822966 0.09722089 0.94684038]
 [0.68136826 0.15414585 0.23226978 0.53799798]
 [0.47548986 0.53776489 0.10566014 0.94742685]
 [0.45104704 0.24401246 0.16240982 0.97662387]]
Array after shifting all elements one position downwards:
 [[0.45104704 0.24401246 0.16240982 0.97662387]
 [0.83756018 0.93822966 0.09722089 0.94684038]
 [0.68136826 0.15414585 0.23226978 0.53799798]
 [0.47548986 0.53776489 0.10566014 0.94742685]]


In [20]:
from scipy.spatial import distance

In [21]:
# Create a 3x3 array with random values
array = np.random.random((3, 3))

# Print the original array
print("Original Array:\n", array)

# Calculate pairwise Euclidean distances between each pair of rows
pairwise_distances = distance.cdist(array, array, 'euclidean')

# Print the pairwise distances
print("Pairwise Euclidean distances between each pair of rows:\n", pairwise_distances)

Original Array:
 [[0.98560055 0.35011324 0.7794954 ]
 [0.41538162 0.46147296 0.67492527]
 [0.9810148  0.56741966 0.12332226]]
Pairwise Euclidean distances between each pair of rows:
 [[0.         0.59032663 0.69123534]
 [0.59032663 0.         0.79713956]
 [0.69123534 0.79713956 0.        ]]
