In [1]:
import numpy as np

In [2]:
# Define a regular NumPy array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a mask to specify which values to mask
mask = np.array([False, True, False, True, False, True, False, True, False, True])

# Create a masked array using the regular array and the mask
masked_array = np.ma.masked_array(data, mask=mask)

# Print the original array and the masked array
print("Original Array:")
print(data)

print("\nMasked Array:")
print(masked_array)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10]

Masked Array:
[1 -- 3 -- 5 -- 7 -- 9 --]


In [3]:
# Create a regular NumPy array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a mask to specify which values to mask
mask = np.array([False, True, False, True, False, True, False, True, False, True])

# Create a masked array using the regular array and the mask
masked_array = np.ma.masked_array(data, mask=mask)

# Fill the masked values with a specified number (e.g., -1)
filled_array = np.ma.filled(masked_array, fill_value=-1)

# Print the original masked array and the filled array
print("Original Masked Array:")
print(masked_array)

print("\nFilled Array:")
print(filled_array)

Original Masked Array:
[1 -- 3 -- 5 -- 7 -- 9 --]

Filled Array:
[ 1 -1  3 -1  5 -1  7 -1  9 -1]


In [4]:
# Create a regular NumPy array
data = np.array([1, 2, 3, 4, 5, np.nan, 7, 8, 9, 10])

# Create a mask to specify which values to mask
mask = np.isnan(data)

# Create a masked array using the regular array and the mask
masked_array = np.ma.masked_array(data, mask=mask)

# Compute the mean of the masked array, ignoring the masked values
mean_value = np.ma.mean(masked_array)

# Print the original array, the masked array, and the computed mean
print("Original Array:")
print(data)

print("\nMasked Array:")
print(masked_array)

print("\nMean of the Masked Array, Ignoring Masked Values:")
print(mean_value)

Original Array:
[ 1.  2.  3.  4.  5. nan  7.  8.  9. 10.]

Masked Array:
[1.0 2.0 3.0 4.0 5.0 -- 7.0 8.0 9.0 10.0]

Mean of the Masked Array, Ignoring Masked Values:
5.444444444444445


In [5]:
# Create a regular NumPy array
data = np.array([1, 2, 3, 4, 5, np.nan, 7, 8, 9, 10])

# Create a mask to specify which values to mask
mask = np.isnan(data)

# Create a masked array using the regular array and the mask
masked_array = np.ma.masked_array(data, mask=mask)

# Compute the mean of the masked array, ignoring the masked values
mean_value = np.ma.mean(masked_array)

# Print the original array, the masked array, and the computed mean
print("Original Array:")
print(data)

print("\nMasked Array:")
print(masked_array)

print("\nMean of the Masked Array, Ignoring Masked Values:")
print(mean_value)

Original Array:
[ 1.  2.  3.  4.  5. nan  7.  8.  9. 10.]

Masked Array:
[1.0 2.0 3.0 4.0 5.0 -- 7.0 8.0 9.0 10.0]

Mean of the Masked Array, Ignoring Masked Values:
5.444444444444445


In [6]:
# Create a regular NumPy array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Specify the value above which elements will be masked
threshold_value = 5

# Create a mask where all elements greater than the specified value are masked
mask = data > threshold_value

# Create a masked array using the regular array and the mask
masked_array = np.ma.masked_array(data, mask=mask)

# Print the original array and the masked array
print("Original Array:")
print(data)

print("\nMasked Array (elements > 5 are masked):")
print(masked_array)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10]

Masked Array (elements > 5 are masked):
[1 2 3 4 5 -- -- -- -- --]


In [7]:
# Create a regular NumPy array with some NaN values
data = np.array([1, 2, 3, np.nan, 5, 6, np.nan, 8, 9, 10])

# Create a mask to specify which values to mask (e.g., NaN values)
mask = np.isnan(data)

# Create a masked array using the regular array and the mask
masked_array = np.ma.masked_array(data, mask=mask)

# Compute the mean of the unmasked elements
mean_value = masked_array.mean()

# Replace all masked values with the mean of the unmasked elements
filled_array = masked_array.filled(mean_value)

# Print the original array, the masked array, and the filled array
print("Original Array:")
print(data)

print("\nMasked Array:")
print(masked_array)

print("\nFilled Array (masked values replaced with mean):")
print(filled_array)

Original Array:
[ 1.  2.  3. nan  5.  6. nan  8.  9. 10.]

Masked Array:
[1.0 2.0 3.0 -- 5.0 6.0 -- 8.0 9.0 10.0]

Filled Array (masked values replaced with mean):
[ 1.   2.   3.   5.5  5.   6.   5.5  8.   9.  10. ]
