In [1]:
import numpy as np

In [14]:
import time

In [2]:
# Define a custom function to compute x^2 + 2x + 1
def compute_expression(x):
    return x**2 + 2*x +1

# Create a ufunc from the custom function using np.frompyfunc
compute_ufunc = np.frompyfunc(compute_expression, 1, 1)

# Create a 1D NumPy array of integers
array_1d = np.array([1, 2, 3, 4, 5])

# Apply the custom ufunc to the 1D array
result_array = compute_ufunc(array_1d)

# Print the original array and the resulting array
print('Original 1D array:', array_1d)
print('Resulting array after applying compute_ufunc:', result_array)

Original 1D array: [1 2 3 4 5]
Resulting array after applying compute_ufunc: [4 9 16 25 36]


In [3]:
# Create a 1D NumPy array of integers
array_1d = np.array([1, 2, 3, 4, 5])

# Apply the np.exp ufunc to the array
exp_array = np.exp(array_1d)

# Apply the np.log ufunc to the resulting array from np.exp
log_array = np.log(exp_array)

# Apply the np.sqrt ufunc to the resulting arrays from np.log
sqrt_array = np.sqrt(log_array)

# Print the original array and the resulting arrays after each transformation
print('Original 1D array:', array_1d)
print('Array after applying np.exp:', exp_array)
print('Array after applying np.log:', log_array)
print('Array after applying np.sqrt:', sqrt_array)

Original 1D array: [1 2 3 4 5]
Array after applying np.exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Array after applying np.log: [1. 2. 3. 4. 5.]
Array after applying np.sqrt: [1.         1.41421356 1.73205081 2.         2.23606798]


In [4]:
# Use the np.add.reduce ufunc to compute the sum of all elements in the array
sum_of_elements = np.add.reduce(array_1d)

# Print the original array and the sum of its elements 
print('Original 1D array:', array_1d)
print('Sum of all elements using np.add.reduce:', sum_of_elements)

Original 1D array: [1 2 3 4 5]
Sum of all elements using np.add.reduce: 15


In [5]:
# Use the np.multiply.accumulate ufunc to compute the cumulative product of elements in the array
cumulative_product = np.multiply.accumulate(array_1d)

# Print the original array and the cumulative product of its elements
print('Original 1D array:', array_1d)
print('Cumulative product using np.multiply.accumulate:', cumulative_product)

Original 1D array: [1 2 3 4 5]
Cumulative product using np.multiply.accumulate: [  1   2   6  24 120]


In [8]:
# Create two 1D NumPy arrays
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

# Use the np.subtract.outer ufunc to compute the outer subtraction
outer_subtraction = np.subtract.outer(array_1, array_2) 

# Print the original arrays and the resulting outer subtraction array
print('Array 1:', array_1)
print('Array 2:', array_2)
print('Outer subtraction of Array 1 and Array 2:\n', outer_subtraction)

Array 1: [1 2 3]
Array 2: [4 5 6]
Outer subtraction of Array 1 and Array 2:
 [[-3 -4 -5]
 [-2 -3 -4]
 [-1 -2 -3]]


In [11]:
# Compute the dot product using np.dot
dot_product = np.dot(array_1, array_2)

# Define a custom ufunc to compute the dot product
def custom_dot(x, y):
    return np.sum(np.multiply(x, y))

# Create a ufunc from the custom function using np.frompyfunc
custom_dot_ufunc = np.frompyfunc(custom_dot, 2, 1)

# Verify the dot product using the custom ufunc
verified_dot_product = custom_dot_ufunc(array_1, array_2)

# Print the original arrays, the np.dot result, and the verified result
print('Array 1:', array_1)
print('Array 2:', array_2)
print('Dot product using np.dot:', dot_product)
print('Dot product using custom ufunc:', verified_dot_product)

Array 1: [1 2 3]
Array 2: [4 5 6]
Dot product using np.dot: 32
Dot product using custom ufunc: [4 10 18]


In [12]:
# Create a 3D NumPy array of shape (3, 4, 5) with random integers
array_3d = np.random.randint(1, 10, size=(3, 4, 5))

# Create a 1D NumPy array with random integers
array_1d = np.random.randint(1, 10, size=5)

# Use the np.divide ufunc to divide each 2D slice of the 3D array by the 1D array
result_array = np.divide(array_3d, array_1d)

# Print the original arrays and the resulting array
print('Original 3D array:\n', array_3d)
print('1D array:\n', array_1d)
print('Resulting array after dividing each 3D slice by the 1D array:\n', result_array)

Original 3D array:
 [[[3 3 2 7 5]
  [3 4 8 2 7]
  [2 6 3 6 9]
  [2 9 5 3 2]]

 [[4 1 8 1 2]
  [4 5 5 2 6]
  [9 7 1 3 3]
  [8 9 2 2 9]]

 [[7 9 3 9 7]
  [9 7 5 4 4]
  [8 8 8 9 1]
  [3 6 4 6 2]]]
1D array:
 [7 2 6 1 1]
Resulting array after dividing each 3D slice by the 1D array:
 [[[0.42857143 1.5        0.33333333 7.         5.        ]
  [0.42857143 2.         1.33333333 2.         7.        ]
  [0.28571429 3.         0.5        6.         9.        ]
  [0.28571429 4.5        0.83333333 3.         2.        ]]

 [[0.57142857 0.5        1.33333333 1.         2.        ]
  [0.57142857 2.5        0.83333333 2.         6.        ]
  [1.28571429 3.5        0.16666667 3.         3.        ]
  [1.14285714 4.5        0.33333333 2.         9.        ]]

 [[1.         4.5        0.5        9.         7.        ]
  [1.28571429 3.5        0.83333333 4.         4.        ]
  [1.14285714 4.         1.33333333 9.         1.        ]
  [0.42857143 3.         0.66666667 6.         2.        ]]]


In [13]:
# Define the custom ufunc
def custom_func(x, y):
    return 3 * x + 4 * y

# Convert the Python function to a NumPy ufunc
custom_ufunc = np.frompyfunc(custom_func, 2, 1)

# Create two 2D NumPy arrays
array_x = np.array([[1, 2], [3, 4]])
array_y = np.array([[5, 6], [7, 8]])

# Apply the custom ufunc to the 2D arrays with broadcasting
result_array = custom_ufunc(array_x, array_y)

# Convert the result to a numeric type array if needed
result_array = result_array.astype(np.float64)

# Print the input arrays and the result array
print("Array X:")
print(array_x)

print("\nArray Y:")
print(array_y)

print("\nResult Array (3x + 4y):")
print(result_array)

Array X:
[[1 2]
 [3 4]]

Array Y:
[[5 6]
 [7 8]]

Result Array (3x + 4y):
[[23. 30.]
 [37. 44.]]


In [15]:
# Define the custom ufunc for element-wise addition
def custom_add(x, y):
    return x + y

# Convert the Python function to a NumPy ufunc
custom_ufunc_add = np.frompyfunc(custom_add, 2, 1)

# Create two large NumPy arrays
size = 1000000
array_x = np.random.rand(size)
array_y = np.random.rand(size)

# Performance comparison using standard Python loop
start_time = time.time()
result_loop = np.empty(size)
for i in range(size):
    result_loop[i] = array_x[i] + array_y[i]
time_loop = time.time() - start_time

# Performance comparison using custom ufunc
start_time = time.time()
result_ufunc = custom_ufunc_add(array_x, array_y)
result_ufunc = result_ufunc.astype(np.float64)  # Convert to numeric type if needed
time_ufunc = time.time() - start_time

# Print the results
print(f"Time taken using standard Python loop: {time_loop:.6f} seconds")
print(f"Time taken using custom ufunc: {time_ufunc:.6f} seconds")

# Verify the results are the same
assert np.allclose(result_loop, result_ufunc), "Results do not match!"
print("Both methods produce the same results.")

Time taken using standard Python loop: 0.301851 seconds
Time taken using custom ufunc: 0.103027 seconds
Both methods produce the same results.
