In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3]) 
y = np.array([[10], [20], [30]])

result = x+y
result

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [3]:
# Create a 2D array x with shape (3, 4)
x = np.array([[5, 6, 7, 8], [1, 2, 3, 4], [9, 10, 11, 12]])

# Create a 1D array y with shape (4,)
y = np.array([1, 2, 3, 4])

x-y

array([[4, 4, 4, 4],
       [0, 0, 0, 0],
       [8, 8, 8, 8]])

In [4]:
# Create a 3D array a with shape (2, 3, 4)
a = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],

              [[13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]]])

# Create a 1D array b with shape (4,)
b = np.array([2, 3, 4, 5])

a*b

array([[[  2,   6,  12,  20],
        [ 10,  18,  28,  40],
        [ 18,  30,  44,  60]],

       [[ 26,  42,  60,  80],
        [ 34,  54,  76, 100],
        [ 42,  66,  92, 120]]])

In [5]:
# Create a 2D array with shape (5, 5)
array_2d = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20],
                     [21, 22, 23, 24, 25]])

# Define a scalar value
scalar = 10

result = array_2d + scalar
result

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [6]:
# Create a 1D array x
x = np.array([1, 2, 3])

# Create a 1D array y
y = np.array([4, 5, 6, 7, 8, 9])

# Reshape x to be a column vector (3, 1)
x_reshaped = x.reshape(3, 1)

# Reshape y to be a row vector (1, 6)
y_reshaped = y.reshape(1, 6)


In [7]:
x_reshaped

array([[1],
       [2],
       [3]])

In [8]:
y_reshaped

array([[4, 5, 6, 7, 8, 9]])

In [9]:
x_reshaped*y_reshaped

array([[ 4,  5,  6,  7,  8,  9],
       [ 8, 10, 12, 14, 16, 18],
       [12, 15, 18, 21, 24, 27]])

In [10]:
# Create a 2D array x with shape (4, 3)
x = np.array([[8, 16, 24],
              [2, 4, 6],
              [12, 24, 36],
              [4, 8, 12]])

# Create a 1D array y with shape (4,)
y = np.array([2, 2, 3, 4])

# Reshape y to be a column vector (4, 1) for broadcasting
y_reshaped = y.reshape(4, 1)

# Divide each column of x by y using broadcasting
result = x / y_reshaped
result

array([[ 4.,  8., 12.],
       [ 1.,  2.,  3.],
       [ 4.,  8., 12.],
       [ 1.,  2.,  3.]])

In [11]:
# Initialize the 2D array of shape (3, 5)
array_2d = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15]])

# Initialize the 1D array of shape (3,)
array_1d = np.array([1, 2, 3])

# Transpose the 2D array to get shape (5, 3)
transposed_array = np.transpose(array_2d)

transposed_array+array_1d

array([[ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17],
       [ 6, 12, 18]])

In [13]:
# Initialize the 3D array of shape (2, 3, 4)
array_3d = np.array([[[ 1,  2,  3,  4],
                      [ 5,  6,  7,  8],
                      [ 9, 10, 11, 12]],

                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

# Initialize the 1D array of shape (3,)
array_1d = np.array([1, 2, 3])

# Subtract the 1D array from each 2D slice of the 3D array
# Broadcasting is used here to subtract 1D array from each 2D slice of 3D array
result_array = array_3d - array_1d[:, np.newaxis]

# Display the result
print(result_array)

[[[ 0  1  2  3]
  [ 3  4  5  6]
  [ 6  7  8  9]]

 [[12 13 14 15]
  [15 16 17 18]
  [18 19 20 21]]]


In [14]:
# Initialize two 1D arrays of shape (5,)
x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 20, 30, 40, 50])

# Reshape the arrays to (5, 1) and (1, 5) respectively
x_reshaped = x.reshape((5, 1))
y_reshaped = y.reshape((1, 5))

# Perform element-wise addition using broadcasting
result_array = x_reshaped + y_reshaped

# Display the result
print(result_array)

[[11 21 31 41 51]
 [12 22 32 42 52]
 [13 23 33 43 53]
 [14 24 34 44 54]
 [15 25 35 45 55]]


In [15]:
# Initialize the 2D array of shape (6, 4)
x = np.array([[12, 24, 36, 48],
              [10, 20, 30, 40],
              [8, 16, 24, 32],
              [6, 12, 18, 24],
              [4, 8, 12, 16],
              [2, 4, 6, 8]])

# Initialize the 1D array of shape (4,)
y = np.array([2, 4, 6, 8])

# Perform element-wise division using broadcasting
result_array = x / y

# Display the result
print(result_array)

[[6. 6. 6. 6.]
 [5. 5. 5. 5.]
 [4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]
