In [1]:
import numpy as np

In [2]:
# Create a 2D NumPy array of shape (5, 5) with random integers
array_2d = np.random.randint(0, 100, size=(5, 5))

# Define the condition to find elements greater than 50
condition = array_2d > 50

# Use np.nonzero to find indices of elements that satisfy the condition
indices = np.nonzero(condition)

# Use the indices for advanced indexing
selected_elements = array_2d[indices]

# Print the original array, the condition, indices, and the selected elements
print('Original 2D array:\n', array_2d)
print('Condition (elements > 50):\n', condition)
print('Indices of elements > 50:\n', indices)
print('Selected elements using advanced indexing:\n', selected_elements)

Original 2D array:
 [[80 91 74 26  2]
 [12 13 26 56 40]
 [80 47 28 52 87]
 [79  0 15 75 43]
 [90 74 66 45 77]]
Condition (elements > 50):
 [[ True  True  True False False]
 [False False False  True False]
 [ True False False  True  True]
 [ True False False  True False]
 [ True  True  True False  True]]
Indices of elements > 50:
 (array([0, 0, 0, 1, 2, 2, 2, 3, 3, 4, 4, 4, 4], dtype=int64), array([0, 1, 2, 3, 0, 3, 4, 0, 3, 0, 1, 2, 4], dtype=int64))
Selected elements using advanced indexing:
 [80 91 74 56 80 52 87 79 75 90 74 66 77]


In [3]:
# Create a 4D NumPy array of shape (4, 4, 4, 4) with random integers
array_4d = np.random.randint(0, 100, size=(4, 4, 4, 4))

# Define indices to extract subarrays
depth_indices = np.array([0, 2])
row_indices = np.array([1, 3])
col_indices = np.array([0, 2])
slice_indices = np.array([1, 3])

# Use integer indexing to extract smaller subarrays
subarray = array_4d[depth_indices[:, np.newaxis, np.newaxis, np.newaxis],
                    row_indices[:, np.newaxis, np.newaxis],
                    col_indices[:, np.newaxis],
                    slice_indices]

# Print the original array shape and the extracted subarray
print('Original 4D array shape:', array_4d.shape)
print('Extracted subarray shape:', subarray.shape)
print('Extracted subarray:\n', subarray)

Original 4D array shape: (4, 4, 4, 4)
Extracted subarray shape: (2, 2, 2, 2)
Extracted subarray:
 [[[[77 71]
   [11 50]]

  [[18 90]
   [31  4]]]


 [[[64 53]
   [48 75]]

  [[28 78]
   [ 2 71]]]]


In [4]:
# Create a 3D NumPy array of shape (4, 5, 6) with random integers
array_3d = np.random.randint(0, 100, size=(4, 5, 6))

# Use slicing to select a specific slice along the first axis
slice_2d = array_3d[2, :, :]

# Define the row and column indices to further index into the 2D slice
row_indices = np.array([0, 2, 4])
col_indices = np.array([1, 3, 5])

# Use integer indexing to select specific elements from the 2D slice
selected_elements = slice_2d[row_indices, col_indices]

# Print the original array, the 2D slice, and the selected elements
print('Original 3D array:\n', array_3d)
print('2D slice (3rd slice along first axis):\n', slice_2d)
print('Row indices:', row_indices)
print('Column indices:', col_indices)
print('Selected elements from 2D slice:\n', selected_elements)

Original 3D array:
 [[[69 17 96 15  5 31]
  [74 57 96 45 21 99]
  [43 92 57 35 61 43]
  [69 55  0 46 25 78]
  [86 91 14 47 56 31]]

 [[37 21 39 71 95 25]
  [73 58 91  4 53 35]
  [22  9 25 46 26  7]
  [71 56 77  3 26 51]
  [64 34 28 20 81 42]]

 [[90 61 98 67 17 23]
  [41 16 78  9 31 88]
  [84 42 88 70 94 56]
  [82 87 10 87 41 12]
  [10 45  2 71 82 15]]

 [[38 23 81 65 98 66]
  [75 14 26 33 48 40]
  [ 1  3  9 53 51 29]
  [71 39 43  1 86 31]
  [75 54 31 61 74 10]]]
2D slice (3rd slice along first axis):
 [[90 61 98 67 17 23]
 [41 16 78  9 31 88]
 [84 42 88 70 94 56]
 [82 87 10 87 41 12]
 [10 45  2 71 82 15]]
Row indices: [0 2 4]
Column indices: [1 3 5]
Selected elements from 2D slice:
 [61 70 15]


In [5]:
# Create a 5D NumPy array of shape (3, 4, 2, 3, 5) with random integers
array_5d = np.random.randint(0, 100, size=(3, 4, 2, 3, 5))

# Define a condition on the entire 5D array
# For example, select elements where the values are greater than 50
condition = array_5d > 50

# Use boolean indexing to select elements along specific dimensions based on the condition
selected_elements = array_5d[condition]

# Print the shape of the original array, the condition array, and the selected elements
print('Original 5D array shape:', array_5d.shape)
print('Condition (elements > 50):\n', condition)
print('Selected elements based on condition:\n', selected_elements)
print('Shape of selected elements:', selected_elements.shape)

Original 5D array shape: (3, 4, 2, 3, 5)
Condition (elements > 50):
 [[[[[False  True  True False False]
    [False  True  True  True False]
    [False False False False  True]]

   [[False False False  True  True]
    [False  True False  True  True]
    [ True  True  True False  True]]]


  [[[ True  True False  True  True]
    [False  True  True  True  True]
    [ True False False False  True]]

   [[False False False  True False]
    [False False  True  True  True]
    [False False  True  True  True]]]


  [[[ True False  True  True False]
    [False False False False False]
    [False  True False  True False]]

   [[False False  True False False]
    [ True  True  True False  True]
    [ True False  True False  True]]]


  [[[ True False False False False]
    [ True False False False  True]
    [False False False  True  True]]

   [[ True False False  True False]
    [False  True False False False]
    [ True False  True  True False]]]]



 [[[[False  True False False False]
    [

In [6]:
# Create a 2D NumPy array of shape (5, 5) with random integers
array_2d = np.random.randint(0, 100, size=(5, 5))

# Define a mask array to select elements that are greater than 50
mask = array_2d > 50

# Use the mask array for indexing to select elements that match the mask criteria
selected_elements = array_2d[mask]

# Print the original array, the mask array, and the selected elements
print('Original 2D array:\n', array_2d)
print('Mask array (elements > 50):\n', mask)
print('Selected elements using the mask:\n', selected_elements)

Original 2D array:
 [[96 15 57 56 80]
 [13 99  4 48 43]
 [14 24 89 17 12]
 [21 57 25 77 93]
 [18 51 64 47 99]]
Mask array (elements > 50):
 [[ True False  True  True  True]
 [False  True False False False]
 [False False  True False False]
 [False  True False  True  True]
 [False  True  True False  True]]
Selected elements using the mask:
 [96 57 56 80 99 89 57 77 93 51 64 99]
