In [1]:
import numpy as np

In [2]:
# Generate two large 1D NumPy arrays with random integers
array1 = np.random.randint(1, 1000, size=1000)
array2 = np.random.randint(1, 1000, size=1000)

# Function to calculate the outer product using nested for loops
def outer_product_with_loops(arr1, arr2):
    result = np.empty((len(arr1), len(arr2)), dtype=int)
    for i in range(len(arr1)):
        for j in range(len(arr2)):
            result[i, j] = arr1[i] * arr2[j]
    return result

# Calculate the outer product using the nested for loops method
outer_with_loops = outer_product_with_loops(array1, array2)

# Calculate the outer product using NumPy's outer() function
outer_with_numpy = np.outer(array1, array2)

# Display the first 10x10 section of the result to verify
print("Outer product using for loops (first 10x10 elements):")
print(outer_with_loops[:10, :10])

print("Outer product using NumPy (first 10x10 elements):")
print(outer_with_numpy[:10, :10])

Outer product using for loops (first 10x10 elements):
[[164280 283272 243904 251304 175528  42920  63640 253376 245680 181448]
 [513930 886182 763024 786174 549118 134270 199090 792656 768580 567638]
 [107670 185658 159856 164706 115042  28130  41710 166064 161020 118922]
 [143190 246906 212592 219042 152994  37410  55470 220848 214140 158154]
 [109890 189486 163152 168102 117414  28710  42570 169488 164340 121374]
 [ 94905 163647 140904 145179 101403  24795  36765 146376 141930 104823]
 [301920 520608 448256 461856 322592  78880 116960 465664 451520 333472]
 [168720 290928 250496 258096 180272  44080  65360 260224 252320 186352]
 [400155 689997 594104 612129 427553 104545 155015 617176 598430 441973]
 [244755 422037 363384 374409 261513  63945  94815 377496 366030 270333]]
Outer product using NumPy (first 10x10 elements):
[[164280 283272 243904 251304 175528  42920  63640 253376 245680 181448]
 [513930 886182 763024 786174 549118 134270 199090 792656 768580 567638]
 [107670 185658 159

In [3]:
# Generate a large 1D NumPy array with random integers
large_array = np.random.randint(1, 1000, size=1000000)

# Function to compute variance using a for loop
def variance_with_loop(arr):
    mean = np.mean(arr)  # Calculate the mean of the array
    variance = 0
    for i in range(len(arr)):
        variance += (arr[i] - mean) ** 2
    variance /= len(arr)  # Divide by the number of elements to get the variance
    return variance

# Compute variance using the for loop method
variance_with_loop_result = variance_with_loop(large_array)

# Compute variance using NumPy's built-in var() function
variance_with_numpy = np.var(large_array)

# Display the results
print(f"Variance using for loop: {variance_with_loop_result}")
print(f"Variance using NumPy: {variance_with_numpy}")

Variance using for loop: 83142.20872364442
Variance using NumPy: 83142.20872365095


In [4]:
# Generate two large 2D NumPy arrays with random integers
array1 = np.random.randint(1, 100, size=(500, 500))
array2 = np.random.randint(1, 100, size=(500, 500))

# Function to calculate the matrix product using nested for loops
def matrix_product_with_loops(A, B):
    result = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i, j] += A[i, k] * B[k, j]
    return result

# Calculate the matrix product using the nested for loops method
product_with_loops = matrix_product_with_loops(array1, array2)

# Calculate the matrix product using NumPy's matmul() function
product_with_numpy = np.matmul(array1, array2)

# Display first 5x5 section of the result to verify
print("Matrix product using for loops (first 5x5 elements):")
print(product_with_loops[:5, :5])

print("Matrix product using NumPy (first 5x5 elements):")
print(product_with_numpy[:5, :5])

Matrix product using for loops (first 5x5 elements):
[[1235763. 1226928. 1236034. 1223299. 1271346.]
 [1235504. 1180010. 1262045. 1241707. 1270678.]
 [1190945. 1181670. 1197489. 1198292. 1235333.]
 [1233772. 1240787. 1238815. 1221594. 1281075.]
 [1235239. 1228222. 1237097. 1207206. 1257879.]]
Matrix product using NumPy (first 5x5 elements):
[[1235763 1226928 1236034 1223299 1271346]
 [1235504 1180010 1262045 1241707 1270678]
 [1190945 1181670 1197489 1198292 1235333]
 [1233772 1240787 1238815 1221594 1281075]
 [1235239 1228222 1237097 1207206 1257879]]


In [5]:
# Generate a large 1D NumPy array with random integers
large_array = np.random.randint(1, 1000000, size=1000000)

# Function to reverse the array using a for loop
def reverse_with_loop(arr):
    reversed_array = np.empty_like(arr)
    for i in range(len(arr)):
        reversed_array[i] = arr[len(arr) - 1 - i]
    return reversed_array

# Reverse the array using the for loop method
reversed_with_loop = reverse_with_loop(large_array)

# Reverse the array using NumPy's slicing operations
reversed_with_numpy = large_array[::-1]

# Display first 10 elements of the reversed arrays to verify
print("First 10 elements of the array reversed using for loop:")
print(reversed_with_loop[:10])

print("First 10 elements of the array reversed using NumPy slicing:")
print(reversed_with_numpy[:10])

First 10 elements of the array reversed using for loop:
[ 12461 527041 704880 554220 523678 283159 915335 975670 954264 169906]
First 10 elements of the array reversed using NumPy slicing:
[ 12461 527041 704880 554220 523678 283159 915335 975670 954264 169906]
