In [1]:
import numpy as np

In [2]:
# Define the two arrays
nums1 = np.array([[1, 2], [3, 4], [5, 6]])
nums2 = np.array([7, 8])
print("Original arrays:")
print(nums1)
print(nums2)

# Find the dot product
result = np.dot(nums1, nums2)

# Print the result
print("Dot product of the said two arrays:")
print(result)

Original arrays:
[[1 2]
 [3 4]
 [5 6]]
[7 8]
Dot product of the said two arrays:
[23 53 83]


In [3]:
# Creating a 3x3 identity matrix
matrix = np.identity(3)
print("3x3 identity matrix:")
print(matrix)

# stacking the matrix vertically
vert_stack = np.vstack((matrix, matrix, matrix))

# stacking the matrix horizontally
horz_stack = np.hstack((matrix, matrix, matrix))

print("Vertical Stack:\n", vert_stack)
print("Horizontal Stack:\n", horz_stack)

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Vertical Stack:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Horizontal Stack:
 [[1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]]


In [4]:
arr = np.random.rand(4, 4)
arr

array([[0.57413902, 0.60979733, 0.18055999, 0.17131714],
       [0.8468092 , 0.137273  , 0.87563478, 0.15756234],
       [0.77121901, 0.00760581, 0.0758423 , 0.4372162 ],
       [0.58586738, 0.27539877, 0.2990527 , 0.26607218]])

In [8]:
row_sum = np.sum(arr, axis=1)
row_sum

array([1.53581349, 2.01727932, 1.29188333, 1.42639103])

In [9]:
arr = np.random.rand(3, 3)
arr

array([[0.30074624, 0.36387967, 0.87273676],
       [0.43871541, 0.85032349, 0.76705354],
       [0.59647335, 0.29095292, 0.40487203]])

In [10]:
row_means = np.mean(arr, axis=1, keepdims=True)
row_means

array([[0.51245422],
       [0.68536415],
       [0.4307661 ]])

In [11]:
arr_subtracted = arr - row_means
arr_subtracted

array([[-0.21170798, -0.14857455,  0.36028254],
       [-0.24664874,  0.16495934,  0.0816894 ],
       [ 0.16570725, -0.13981318, -0.02589407]])

In [12]:
# Generate a 3x3 array with random values
nums = np.random.rand(3, 3)
print("Original array elements:")
print(nums)
# Compute the mean of each column
col_means = np.mean(nums, axis=0)
print("\nMean of each row:")
print(col_means)
# Subtract the mean of each column from each element
print("\nSubtract the mean of each row from each element:")
result = nums - col_means
print(result)

Original array elements:
[[0.5075901  0.26133991 0.98837156]
 [0.6439155  0.84599522 0.99168014]
 [0.54505148 0.08367471 0.10370237]]

Mean of each row:
[0.56551903 0.39700328 0.69458469]

Subtract the mean of each row from each element:
[[-0.05792893 -0.13566337  0.29378687]
 [ 0.07839648  0.44899194  0.29709545]
 [-0.02046754 -0.31332857 -0.59088232]]


In [13]:
# create 5x5 array with random values
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
# normalize row-wise
norm_arr = nums / np.linalg.norm(nums, axis=1, keepdims=True)
print("\nNormalize Array row-wise:")
print(norm_arr)

Original array elements:
[[0.82670147 0.30280261 0.01949584 0.59110926 0.04723175]
 [0.33547921 0.59993208 0.87153434 0.07480032 0.10807394]
 [0.69976744 0.64212014 0.83408784 0.91066722 0.70841286]
 [0.28046159 0.60653251 0.23338096 0.55577153 0.04186768]
 [0.24136957 0.94577321 0.86628846 0.8055453  0.90628265]]

Normalize Array row-wise:
[[0.77867935 0.28521316 0.01836335 0.55677242 0.04448811]
 [0.30014434 0.5367433  0.77973863 0.06692186 0.09669088]
 [0.40888814 0.37520367 0.48737424 0.5321211  0.41393983]
 [0.31130862 0.67324299 0.25904975 0.61689898 0.04647256]
 [0.13549288 0.53091005 0.48629126 0.45219307 0.50874201]]


In [14]:
# create 5x5 array with random values
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
# normalize column-wise
norm_arr = nums / np.linalg.norm(nums, axis=0, keepdims=True)
print("\nNormalize Array row-wise:")
print(norm_arr)

Original array elements:
[[0.45176653 0.26339488 0.36664925 0.58427753 0.47583766]
 [0.04687965 0.17729627 0.44914749 0.99834621 0.55235751]
 [0.34753548 0.82122951 0.31694439 0.05196186 0.12505387]
 [0.73488353 0.30385731 0.88828263 0.4433483  0.72635107]
 [0.15930761 0.31152845 0.28816626 0.05164043 0.58038252]]

Normalize Array row-wise:
[[0.47819925 0.2681834  0.32050143 0.47082427 0.40050206]
 [0.04962256 0.18051952 0.39261613 0.80449033 0.46490713]
 [0.36786967 0.83615949 0.2770526  0.04187206 0.10525508]
 [0.77788133 0.30938145 0.77648011 0.35726026 0.61135367]
 [0.16862865 0.31719205 0.2518966  0.04161305 0.48849516]]


In [16]:
# create a 5x5 array with random values
nums = np.random.rand(5, 5)

# compute the mean of each column
col_means = np.mean(nums, axis=0)

# normalize each column by subtracting its mean and dividing by its standard deviation
arr_normalized = (nums - col_means) / np.std(nums, axis=0)

print("Original Array:")
print(nums)
print("\nNormalized Array (column-wise):")
print(arr_normalized)

Original Array:
[[0.87169609 0.80369622 0.93459441 0.24087015 0.88605142]
 [0.01976609 0.04959612 0.97242712 0.9568727  0.62260654]
 [0.10015507 0.9447103  0.6640602  0.20024903 0.53554114]
 [0.71604873 0.35044342 0.19026595 0.64711112 0.46171395]
 [0.98980877 0.20920743 0.91732024 0.38092567 0.48335471]]

Normalized Array (column-wise):
[[ 0.82666314  0.96230373  0.67715365 -0.86336303  1.86656074]
 [-1.29331493 -1.22237012  0.80598021  1.66664148  0.1603168 ]
 [-1.09327163  1.37083008 -0.2440596  -1.00689829 -0.40357654]
 [ 0.43934377 -0.35079722 -1.85740652  0.57209483 -0.88173047]
 [ 1.12057965 -0.75996646  0.61833225 -0.36847498 -0.74157054]]


In [17]:
nums = np.random.rand(3, 3, 3)
print("Original array elements:")
print(nums)
sum_along_last_axis = np.sum(nums, axis=2)
print("\nSum along the last axis:")
print(sum_along_last_axis)

Original array elements:
[[[0.06822519 0.18616035 0.38695016]
  [0.55181683 0.71695235 0.84720263]
  [0.8997301  0.67393002 0.918437  ]]

 [[0.77884291 0.29476766 0.53502498]
  [0.11396971 0.99362498 0.91012821]
  [0.71111164 0.6516499  0.02071606]]

 [[0.23472766 0.10731204 0.79853287]
  [0.03181696 0.31938793 0.39415798]
  [0.53075541 0.86457088 0.92622695]]]

Sum along the last axis:
[[0.64133569 2.11597181 2.49209712]
 [1.60863556 2.0177229  1.3834776 ]
 [1.14057257 0.74536287 2.32155324]]


In [18]:
# create a 5x5 array with random values
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
# sort each row
sorted_arr = np.sort(nums, axis=1)
print("\nSort each row of the said array:")
print(sorted_arr)

Original array elements:
[[0.36491884 0.48433318 0.04939871 0.63993192 0.0288494 ]
 [0.61420027 0.18118178 0.73497348 0.23728802 0.1196635 ]
 [0.26884617 0.86162017 0.5683793  0.38924293 0.18670258]
 [0.32219237 0.84498167 0.63170177 0.12155299 0.10323741]
 [0.00943415 0.43889638 0.74891547 0.21354077 0.61712558]]

Sort each row of the said array:
[[0.0288494  0.04939871 0.36491884 0.48433318 0.63993192]
 [0.1196635  0.18118178 0.23728802 0.61420027 0.73497348]
 [0.18670258 0.26884617 0.38924293 0.5683793  0.86162017]
 [0.10323741 0.12155299 0.32219237 0.63170177 0.84498167]
 [0.00943415 0.21354077 0.43889638 0.61712558 0.74891547]]


In [19]:
# create a 5x5 array with random values
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
# sort each column
arr_sorted = np.sort(nums, axis=0)
# print the sorted array
print("\nSort each column of the said array:")
print(arr_sorted)

Original array elements:
[[0.84865223 0.38904341 0.26816825 0.58535546 0.69617978]
 [0.64225003 0.79280793 0.08289085 0.4237052  0.68577333]
 [0.55050678 0.42405323 0.38001061 0.79455305 0.8308372 ]
 [0.00157041 0.41819714 0.61335714 0.5896129  0.77165235]
 [0.86275565 0.55218718 0.02797883 0.65830371 0.51562615]]

Sort each column of the said array:
[[0.00157041 0.38904341 0.02797883 0.4237052  0.51562615]
 [0.55050678 0.41819714 0.08289085 0.58535546 0.68577333]
 [0.64225003 0.42405323 0.26816825 0.5896129  0.69617978]
 [0.84865223 0.55218718 0.38001061 0.65830371 0.77165235]
 [0.86275565 0.79280793 0.61335714 0.79455305 0.8308372 ]]
