In [1]:
import numpy as np

In [2]:
# Create a 3D NumPy array of shape (3, 4, 5) with random integers
array_3d = np.random.randint(0, 100, size=(3, 4, 5))

# Define the indices to select specific elements along each axis
depth_indices = np.array([0, 1, 2])
row_indices = np.array([1, 2, 3])
column_indices = np.array([2, 3, 4])

# Use integer array indexing to select elements along specific axes
selected_elements = array_3d[depth_indices[:, np.newaxis, np.newaxis], row_indices[:, np.newaxis], column_indices]

# Print the original array and the selected elements
print('Original 3D array:\n', array_3d)
print('Depth indices:\n', depth_indices)
print('Row indices:\n', row_indices)
print('Column indices:\n', column_indices)
print('Selected elements:\n', selected_elements)

Original 3D array:
 [[[ 8  4 89 79 92]
  [34 97 54 63 69]
  [92  3 16 15 52]
  [66 75 29 11 29]]

 [[74 87  4 88 86]
  [ 5 19 46 99 45]
  [ 3 61 52  9 62]
  [97 35 71 71 46]]

 [[32 30 19 88 74]
  [83  0 71 89 23]
  [27 82 72 51 25]
  [ 7 86 38  4 32]]]
Depth indices:
 [0 1 2]
Row indices:
 [1 2 3]
Column indices:
 [2 3 4]
Selected elements:
 [[[54 63 69]
  [16 15 52]
  [29 11 29]]

 [[46 99 45]
  [52  9 62]
  [71 71 46]]

 [[71 89 23]
  [72 51 25]
  [38  4 32]]]


In [3]:
# Create a 2D NumPy array of shape (5, 5) with random integers
array_2d = np.random.randint(0, 100, size=(5,5))

# Define the boolean condition to select elements greater than 50
condition = array_2d > 50

# Define the specific rows to apply the condition
row_indices = np.array([1, 3, 4])

# Use a combination of boolean and integer indexing to select elements
selected_elements = array_2d[row_indices][:, condition[row_indices][0]]

# Print the original array and the selected elements
print('Original 2D array:\n', array_2d)
print('Condition (elements > 50):\n', condition)
print('Row indices:\n', row_indices)
print('Selected elements using combined indexing:\n', selected_elements)

Original 2D array:
 [[48 16 64 30 98]
 [19 96 43 47 57]
 [97 17 19 57  5]
 [28 89 75 50 16]
 [66  5  5 68 26]]
Condition (elements > 50):
 [[False False  True False  True]
 [False  True False False  True]
 [ True False False  True False]
 [False  True  True False False]
 [ True False False  True False]]
Row indices:
 [1 3 4]
Selected elements using combined indexing:
 [[96 57]
 [89 16]
 [ 5 26]]


In [4]:
# Create a 1D NumPy array with random integers
array_1d = np.random.randint(0, 100, size=20)

# Define multiple conditions using logical operators
condition = (array_1d > 30) & (array_1d < 70) | (array_1d % 10 == 0)

# Use boolean indexing to select elements that meet the conditions
selected_elements = array_1d[condition]

# Print the original array and the selected elements
print('Original 1D array:\n', array_1d)
print('Condition (elements > 30 AND < 70 OR divisible by 10):\n', condition)
print('Selected elements:\n', selected_elements)

Original 1D array:
 [71 43 86 13  1 16 60 54  3 84  1 26 82 71  6 99 16 58 55 11]
Condition (elements > 30 AND < 70 OR divisible by 10):
 [False  True False False False False  True  True False False False False
 False False False False False  True  True False]
Selected elements:
 [43 60 54 58 55]


In [5]:
# Create a 2D NumPy array of shape (6, 6) with random integers
array_2d = np.random.randint(0, 100, size=(6, 6))

# Define the row and column indices to slice the array
row_indices = np.arange(2, 5)  # rows from index 2 to 4 (inclusive)
col_indices = np.arange(1, 4)  # columns from index 1 to 3 (inclusive)

# Use slicing in combination with index arrays to select a subarray
subarray = array_2d[row_indices[:, np.newaxis], col_indices]

# Print the original array and the selected subarray
print('Original 2D array:\n', array_2d)
print('Row indices:', row_indices)
print('Column indices:', col_indices)
print('Selected subarray:\n', subarray)

Original 2D array:
 [[18 41 56 10 83 45]
 [54 40  3 97 34 61]
 [45 81 28 10 76 34]
 [51 58 83 46 51  1]
 [49 93 34 92 99 78]
 [61 61 28  8 88 46]]
Row indices: [2 3 4]
Column indices: [1 2 3]
Selected subarray:
 [[81 28 10]
 [58 83 46]
 [93 34 92]]


In [6]:
# Create a 3D NumPy array of shape (4, 4, 4) with random integers
array_3d = np.random.randint(0, 100, size=(4, 4, 4))

# Define the condition to set elements less than 50 to -1
condition = array_3d < 50

# Use boolean indexing to set elements that meet the condition to -1
array_3d[condition] = -1

# Print the original array and the modified array
print('Original 3D array:\n', array_3d)
print('Condition (elements < 50):\n', condition)
print('Modified 3D array with elements < 50 set to -1:\n', array_3d)

Original 3D array:
 [[[93 -1 -1 86]
  [-1 91 54 -1]
  [58 -1 -1 -1]
  [72 -1 94 -1]]

 [[94 70 60 -1]
  [-1 82 86 -1]
  [-1 63 94 50]
  [-1 85 -1 82]]

 [[74 -1 -1 -1]
  [-1 72 57 53]
  [91 77 -1 91]
  [99 -1 -1 70]]

 [[-1 99 93 92]
  [-1 53 -1 -1]
  [-1 -1 -1 -1]
  [87 75 67 -1]]]
Condition (elements < 50):
 [[[False  True  True False]
  [ True False False  True]
  [False  True  True  True]
  [False  True False  True]]

 [[False False False  True]
  [ True False False  True]
  [ True False False False]
  [ True False  True False]]

 [[False  True  True  True]
  [ True False False False]
  [False False  True False]
  [False  True  True False]]

 [[ True False False False]
  [ True False  True  True]
  [ True  True  True  True]
  [False False False  True]]]
Modified 3D array with elements < 50 set to -1:
 [[[93 -1 -1 86]
  [-1 91 54 -1]
  [58 -1 -1 -1]
  [72 -1 94 -1]]

 [[94 70 60 -1]
  [-1 82 86 -1]
  [-1 63 94 50]
  [-1 85 -1 82]]

 [[74 -1 -1 -1]
  [-1 72 57 53]
  [91 77 -1 91]
  [