In [1]:
import pandas as pd
import numpy as np

In [2]:
x1 = np.array(['Python', 'PHP', 'JS', 'EXAMPLES', 'HTML'], dtype=str)
x1

array(['Python', 'PHP', 'JS', 'EXAMPLES', 'HTML'], dtype='<U8')

In [3]:
r = np.char.find(x1, 'P')
r

array([ 0,  0, -1,  4, -1])

In [6]:
# Creating a NumPy array containing strings
x = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype=str)

# Displaying the content of the original array
print("\nOriginal Array:")
print(x)

# Checking if each element contains digits only
r1 = np.char.isdigit(x)

# Checking if each element contains lower case letters only
r2 = np.char.islower(x)

# Checking if each element contains upper case letters only
r3 = np.char.isupper(x)

# Displaying results
print("Digits only =", r1)
print("Lower cases only =", r2)
print("Upper cases only =", r3) 


Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Digits only = [False False False False False  True]
Lower cases only = [False False False False  True False]
Upper cases only = [False  True  True False False False]


In [7]:
s = np.char.startswith(x1, "P")
s

array([ True,  True, False, False, False])

In [8]:
nums = np.array(['1.12', '2.23', '3.71', '4.23', '5.11'], dtype=str)
nums

array(['1.12', '2.23', '3.71', '4.23', '5.11'], dtype='<U4')

In [9]:
np.char.add('00', nums)

array(['001.12', '002.23', '003.71', '004.23', '005.11'], dtype='<U6')

In [10]:
np.char.rjust(nums, 6, fillchar='0')

array(['001.12', '002.23', '003.71', '004.23', '005.11'], dtype='<U6')

In [11]:
# Creating a NumPy array containing strings
str1 = np.array([['Python-NumPy-Exercises'], ['-Python-']])

# Displaying the original array of string values
print("Original array of string values:") 
print(str1)

# Replacing '-' with '=' character in the array of string values using np.char.replace() and np.char.strip()
print("\nReplace '-' with '=' character in the said array of string values:")
print(np.char.strip(np.char.replace(str1, '-', '==')))

# Replacing '-' with ' ' character in the array of string values using np.char.replace() and np.char.strip()
print("\nReplace '-' with ' ' character in the said array of string values:")
print(np.char.strip(np.char.replace(str1, '-', ' '))) 

Original array of string values:
[['Python-NumPy-Exercises']
 ['-Python-']]

Replace '-' with '=' character in the said array of string values:
[['Python==NumPy==Exercises']
 ['==Python==']]

Replace '-' with ' ' character in the said array of string values:
[['Python NumPy Exercises']
 ['Python']]


In [12]:
# Creating a NumPy array containing string values
str1 = np.array([['Python','NumPy','Exercises'],
                 ['Python','Pandas','Exercises'],
                 ['Python','Machine learning','Python']])

# Displaying the original array of string values
print("Original array of string values:") 
print(str1)

# Counting occurrences of 'Python' row-wise in the array using np.char.count()
print("\nCount 'Python' row wise in the above array of string values:")
print(np.char.count(str1, 'Python')) 

Original array of string values:
[['Python' 'NumPy' 'Exercises']
 ['Python' 'Pandas' 'Exercises']
 ['Python' 'Machine learning' 'Python']]

Count 'Python' row wise in the above array of string values:
[[1 0 0]
 [1 0 0]
 [1 0 1]]


In [17]:
# The string containing student information
student = """01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos"""

# Displaying the original text
print("Original text:") 
print(student)

# Splitting the text into lines and then further splitting by tab ('\t')
text_lines = student.splitlines()
text_lines = [r.split('\t') for r in text_lines]

# Creating a NumPy array from the split text
result = np.array(text_lines, dtype=str)
print("\nArray from the said text:")
print(result) 

Original text:
01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos

Array from the said text:
[['01' 'V' 'Debby Pramod']
 ['02' 'V' 'Artemiy Ellie']
 ['03' 'V' 'Baptist Kamal']
 ['04' 'V' 'Lavanya Davide']
 ['05' 'V' 'Fulton Antwan']
 ['06' 'V' 'Euanthe Sandeep']
 ['07' 'V' 'Endzela Sanda']
 ['08' 'V' 'Victoire Waman']
 ['09' 'V' 'Briar Nur']
 ['10' 'V' 'Rose Lykos']]
