In [1]:
import numpy as np

In [2]:
# Create a 2D NumPu array of shape(5,5) with random integers
array_2d = np.random.randint(0, 100, size=(5, 5))

# Define the row indices to select specific rows
row_indices = np.array([1, 3])

# Use integer indexing with broadcasting to select elements from specific rows and all columns
selected_elements = array_2d[row_indices[:, np.newaxis], np.arange(array_2d.shape[1])]

# Print the original array and the selected elements
print('Original 2D array:\n', array_2d)
print('Selected rows:\n', row_indices)
print('Selected elements from specific rows and all columns:\n', selected_elements)

Original 2D array:
 [[65 47 74 80 19]
 [61 89 84 58 30]
 [ 6 45  4 97 76]
 [71  6 22 65 82]
 [40 27 83 44 19]]
Selected rows:
 [1 3]
Selected elements from specific rows and all columns:
 [[61 89 84 58 30]
 [71  6 22 65 82]]


In [3]:
# Create a 3D NumPy array of shape (3, 4, 5) with random integers
array_3d = np.random.randint(0, 100, size=(3, 4, 5))

# Define the condition to apply on the second axis (axis 1)
condition = array_3d[:, :, 0] > 50

# Use boolean indexing to select elements along the third axis (axis 2)
selected_elements = array_3d[condition]

# Print the original #D array and the selected elements
print('Original 3D array:\n', array_3d)
print('Condition array(elements along second axis where first elements > 50):\n', condition)
print('Selected elements along third axis based on condition:\n', selected_elements)

Original 3D array:
 [[[53 18 79 69 43]
  [ 6 69 82 77 22]
  [90 79  9 37  4]
  [97 75  6 74 71]]

 [[65 46 43 17 16]
  [35 66 62 33 28]
  [62 73 25 96 72]
  [20 71 17 17 36]]

 [[24 55 24 13 31]
  [90 95 62  8 50]
  [77 86 75 35 94]
  [16 89 98 70 99]]]
Condition array(elements along second axis where first elements > 50):
 [[ True False  True  True]
 [ True False  True False]
 [False  True  True False]]
Selected elements along third axis based on condition:
 [[53 18 79 69 43]
 [90 79  9 37  4]
 [97 75  6 74 71]
 [65 46 43 17 16]
 [62 73 25 96 72]
 [90 95 62  8 50]
 [77 86 75 35 94]]


In [4]:
# Create a 2D NumPy array of shape (5, 5) with random integers
array_2d = np.random.randint(0, 100, size=(5, 5))

# Define row and column indices as a tuple of arrays
row_indices = np.array([0, 1, 2, 3])
col_indices = np.array([4, 3, 2, 1])

# Use the tuple of arrays to index and select specific elements
selected_elements = array_2d[row_indices, col_indices]

# Print the original array and the selected elements
print('Original 2D array:\n', array_2d)
print('Row indices:\n', row_indices)
print('Column indices:\n', col_indices)
print('Selected elements:\n', selected_elements)

Original 2D array:
 [[ 2 49 91 32 79]
 [17 59 33 72 62]
 [39  1 23  3 74]
 [34 63 58 35 42]
 [72 73 84 25 60]]
Row indices:
 [0 1 2 3]
Column indices:
 [4 3 2 1]
Selected elements:
 [79 72 23 63]


In [5]:
# Create a 2D NumPy array of shape (5, 5) with random integers
array_2d = np.random.randint(0, 100, size=(5, 5))

# Create two 1D NumPy arrays for cross-indexing
row_indices = np.array([1, 3])
col_indices = np.array([0, 2, 4])

# Use np.ix_ to create an open mesh from the row and column indices
index_grid = np.ix_(row_indices, col_indices)

# Use the index grid to select elements from the 2D array
selected_elements = array_2d[index_grid]

# Print the original array and the selected elements
print('Original 2D array:\n', array_2d)
print('Row indices:\n', row_indices)
print('Column indices:\n', col_indices)
print('Selected elements using np.ix_:\n', selected_elements)

Original 2D array:
 [[95 15  7 64 95]
 [18 51 60  3 55]
 [46 23 72 39 45]
 [91 39 11 33 93]
 [28 11 20 53 77]]
Row indices:
 [1 3]
Column indices:
 [0 2 4]
Selected elements using np.ix_:
 [[18 60 55]
 [91 11 93]]


In [6]:
# Create a 2D NumPy array of shape (5, 5) with random integers
array_2d = np.random.randint(0, 100, size=(5, 5))

# Define the condition to replace elements greater than 50
condition = array_2d > 50

# Define the value to replace the elements that meet the condition
replacement_value = -1

# Use boolean indexing to replace elements that meet the condition
array_2d[condition] = replacement_value

# Print the modified array
print('Modified 2D array:\n', array_2d)

Modified 2D array:
 [[-1 23 -1 -1  4]
 [12 -1 45 -1 -1]
 [-1  1 -1  3 25]
 [ 5 -1 -1 48 41]
 [-1 48 -1 -1 20]]
