In [1]:
import numpy as np

In [2]:
# Create a NumPy array
array_x = np.array([1, 2, 3, 4, 5])

# Create another array to add
array_y = np.array([10, 20, 30, 40, 50])

# Perform in-place addition using np.ad with the out parameter
np.add(array_x, array_y, out=array_x)

# Print the resulting array
print("Result Array after In-Place Addition:")
print(array_x)

Result Array after In-Place Addition:
[11 22 33 44 55]


In [3]:
# Create a NumPy array with NaN values
array_with_nan = np.array([1, 2, np.nan, 4, np.nan, 6])

# Replace NaN values with a specified number, e.g., 0
array_without_nan = np.nan_to_num(array_with_nan, nan=0.0)

# Print the original and modified arrays
print("Original Array with NaN values:")
print(array_with_nan)

print("\nArray after replacing NaN values:")
print(array_without_nan)

Original Array with NaN values:
[ 1.  2. nan  4. nan  6.]

Array after replacing NaN values:
[1. 2. 0. 4. 0. 6.]


In [4]:
# Define a custom function to operate on complex numbers
def custom_complex_operation(z):
    return z.real + z.imag

# Convert the custom function to a NumPy ufunc
custom_ufunc = np.frompyfunc(custom_complex_operation, 1, 1)

# Create a NumPy array of complex numbers
complex_array = np.array([1+2j, 3+4j, 5+6j])

# Apply the custom ufunc to the complex array
result_array = custom_ufunc(complex_array)

# Print the original complex array and the result array
print("Original Complex Array:")
print(complex_array)

print("\nResult Array after applying custom ufunc:")
print(result_array)

Original Complex Array:
[1.+2.j 3.+4.j 5.+6.j]

Result Array after applying custom ufunc:
[3.0 7.0 11.0]


In [5]:
# Create two boolean arrays
array_a = np.array([True, False, True, False])
array_b = np.array([True, True, False, False])

# Combine the boolean arrays using np.logical_and
result_array = np.logical_and(array_a, array_b)

# Print the original boolean arrays and the result array
print("Array A:")
print(array_a)

print("\nArray B:")
print(array_b)

print("\nResult Array after applying np.logical_and:")
print(result_array)

Array A:
[ True False  True False]

Array B:
[ True  True False False]

Result Array after applying np.logical_and:
[ True False False False]


In [6]:
# Create a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Find the maximum element along the specified axis (e.g., axis=0) columns
max_elements_axis0 = np.maximum.reduce(array_2d, axis=0)

# Find the maximum element along the specified axis (e.g., axis=1) rows
max_elements_axis1 = np.maximum.reduce(array_2d, axis=1)

# Print the original 2D array and the results
print("Original 2D Array:")
print(array_2d)

print("\nMaximum elements along axis 0:")
print(max_elements_axis0)

print("\nMaximum elements along axis 1:")
print(max_elements_axis1)

Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Maximum elements along axis 0:
[7 8 9]

Maximum elements along axis 1:
[3 6 9]
