In [1]:
import numpy as np
import pandas as pd

In [3]:
# Create a 3D NumPy array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("Original 3D NumPy array: ", array_3d)
print(type(array_3d))

# Convert the 3D NumPy array to a nested list of lists of lists
list_of_lists = array_3d.tolist()

# Print the list of lists of lists
print("\nlist of lists of lists:")
print(list_of_lists)
print(type(list_of_lists))

Original 3D NumPy array:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>

list of lists of lists:
[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
<class 'list'>


In [4]:
# Define a nested list of lists of lists
list_of_lists = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

print("Original nested list of lists of lists:",list_of_lists)
print(type(list_of_lists))

# Convert the nested list to a 3D NumPy array
print("\nNested list to a 3D NumPy array:")
array_3d = np.array(list_of_lists)

# Print the 3D NumPy array
print(array_3d)
print(type(array_3d))

Original nested list of lists of lists: [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
<class 'list'>

Nested list to a 3D NumPy array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


In [5]:
# Create a Pandas DataFrame with mixed data types
data = {
    'A': [1, 2, 3, 4],
    'B': ['a', 'b', 'c', 'd'],
    'C': [5.0, 6.1, 7.2, 8.3]
}
df = pd.DataFrame(data)

print("Original Pandas DataFrame with mixed data types:",df)
print(type(df))

# Convert the DataFrame to a NumPy array
array = df.to_numpy()
print("\nDataFrame to a NumPy array:")
# Print the NumPy array
print(array)
print(type(array))

Original Pandas DataFrame with mixed data types:    A  B    C
0  1  a  5.0
1  2  b  6.1
2  3  c  7.2
3  4  d  8.3
<class 'pandas.core.frame.DataFrame'>

DataFrame to a NumPy array:
[[1 'a' 5.0]
 [2 'b' 6.1]
 [3 'c' 7.2]
 [4 'd' 8.3]]
<class 'numpy.ndarray'>


In [6]:
# Create a NumPy array
array = np.array([[10, 20], [30, 40], [50, 60]])

# Create a Pandas DataFrame
data = {
    'A': [1, 2, 3],
    'B': ['a', 'b', 'c']
}
df = pd.DataFrame(data)

# Combine the NumPy array and Pandas DataFrame into a single DataFrame
# Adding columns to match the DataFrame structure
array_df = pd.DataFrame(array, columns=['C', 'D'])

# Concatenate both DataFrames
combined_df = pd.concat([df, array_df], axis=1)

# Print the combined DataFrame
print(combined_df)

   A  B   C   D
0  1  a  10  20
1  2  b  30  40
2  3  c  50  60


In [7]:
# Create a Python list
python_list = [1, 2, 3]
print("Original Python list:",python_list)
print(type(python_list))

# Create a NumPy array
numpy_array = np.array([4, 5, 6])
print("\nOriginal NumPy list:",numpy_array)
print(type(numpy_array))

# Append the NumPy array to the Python list
# Convert the NumPy array to a list before appending
combined_list = python_list + numpy_array.tolist()
print("\nCombined list:")

# Print the resulting list
print(combined_list)
print(type(combined_list))

Original Python list: [1, 2, 3]
<class 'list'>

Original NumPy list: [4 5 6]
<class 'numpy.ndarray'>

Combined list:
[1, 2, 3, 4, 5, 6]
<class 'list'>
