In [1]:
import numpy as np

In [2]:
x = np.array([3.1, 3.5, 4.5, 2.9, -3.1, -3.5, -5.9])
x

array([ 3.1,  3.5,  4.5,  2.9, -3.1, -3.5, -5.9])

In [3]:
np.round(x)

array([ 3.,  4.,  4.,  3., -3., -4., -6.])

In [4]:
np.floor(x)

array([ 3.,  3.,  4.,  2., -4., -4., -6.])

In [5]:
np.ceil(x)

array([ 4.,  4.,  5.,  3., -3., -3., -5.])

In [6]:
np.trunc(x)

array([ 3.,  3.,  4.,  2., -3., -3., -5.])

In [7]:
r = [round(elem) for  elem in x]
r

[3, 4, 4, 3, -3, -4, -6]

In [8]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
r = np.cumsum(x)
r

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [10]:
np.cumsum(x, axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [11]:
np.cumsum(x, axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [12]:
np.cumprod(x)

array([  1,   2,   6,  24, 120, 720], dtype=int32)

In [13]:
np.cumprod(x, axis=0)

array([[ 1,  2,  3],
       [ 4, 10, 18]], dtype=int32)

In [14]:
np.cumprod(x, axis=1)

array([[  1,   2,   6],
       [  4,  20, 120]], dtype=int32)

In [15]:
x = np.array([1, 3, 5, 7, 0])
x

array([1, 3, 5, 7, 0])

In [16]:
np.diff(x)

array([ 2,  2,  2, -7])

In [17]:
# Creating an array
x = np.array([1, 3, 5, 7, 0])

# Displaying the original array
print("Original array: ")
print(x)

# Calculating differences between neighboring elements, element-wise, and appending [200] to the end and [0, 0] to the beginning
r1 = np.ediff1d(x, to_begin=[0, 0], to_end=[200])

# Calculating differences between neighboring elements, appending [200] to the end, and inserting [0, 0] at the beginning
r2 = np.insert(np.append(np.diff(x), 200), 0, [0, 0])

# Checking if the resulting arrays r1 and r2 are equivalent
assert np.array_equiv(r1, r2)

# Displaying the resulting array with differences and appended/prepended values
print("Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:")
print(r2) 

Original array: 
[1 3 5 7 0]
Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
[  0   0   2   2   2  -7 200]


In [18]:
# Creating an array of float32 type
x = np.array([1., 2., 3., 4.], np.float32)

# Displaying the original array
print("Original array: ")
print(x)

# Calculating exponential (e^x) for each element of the array x
print("\ne^x, element-wise of the said:")
r = np.exp(x)
print(r) 

Original array: 
[1. 2. 3. 4.]

e^x, element-wise of the said:
[ 2.7182817  7.389056  20.085537  54.59815  ]


In [19]:
# Creating an array of float32 type
x = np.array([1., 2., 3., 4.], np.float32)

# Displaying the original array
print("Original array: ")
print(x)

# Calculating exp(x) - 1 for each element of the array x
print("\nexp(x)-1 for all elements of the said array:")
r1 = np.expm1(x)
r2 = np.exp(x) - 1.

# Asserting whether the results from np.expm1 and np.exp - 1 are close
assert np.allclose(r1, r2)

# Printing the resulting array after exp(x) - 1 calculation
print(r1) 


Original array: 
[1. 2. 3. 4.]

exp(x)-1 for all elements of the said array:
[ 1.7182817  6.389056  19.085537  53.59815  ]


In [20]:
np.exp2(x)

array([ 2.,  4.,  8., 16.], dtype=float32)

In [21]:
2**x

array([ 2.,  4.,  8., 16.], dtype=float32)

In [22]:
# Creating an array consisting of 1, e, and e^2
x = np.array([1, np.e, np.e**2])

# Displaying the original array
print("Original array: ")
print(x)

# Calculating natural logarithm (base e) of the array elements
print("\nNatural log =", np.log(x))

# Calculating common logarithm (base 10) of the array elements
print("Common log =", np.log10(x))

# Calculating base 2 logarithm of the array elements
print("Base 2 log =", np.log2(x))

Original array: 
[1.         2.71828183 7.3890561 ]

Natural log = [0. 1. 2.]
Common log = [0.         0.43429448 0.86858896]
Base 2 log = [0.         1.44269504 2.88539008]


In [23]:
# Creating an array with two very small numbers
x = np.array([1e-99, 1e-100])

# Displaying the original array
print("Original array: ")
print(x)

# Calculating natural logarithm of one plus each element in the array
print("\nNatural logarithm of one plus each element:")
print(np.log1p(x)) 

Original array: 
[1.e-099 1.e-100]

Natural logarithm of one plus each element:
[1.e-099 1.e-100]


In [24]:
# Creating an array with integer values ranging from -4 to 4
x = np.array([-4, -3, -2, -1, 0, 1, 2, 3, 4])

# Displaying the original array
print("Original array: ")
print(x)

# Calculating sign bit of each element in the array using np.signbit()
r1 = np.signbit(x)

# Comparing if each element is less than zero to determine sign bit as a boolean array
r2 = x < 0

# Verifying if both approaches yield the same result
assert np.array_equiv(r1, r2)

# Displaying the sign bit of each element in the array
print(r1)

Original array: 
[-4 -3 -2 -1  0  1  2  3  4]
[ True  True  True  True False False False False False]


In [25]:

# Creating an array with integer values from -1 to 2
x1 = np.array([-1, 0, 1, 2])

# Displaying the original array x1
print("Original array: ")
print(x1)

# Assigning a floating-point value to x2
x2 = -2.1

# Displaying the sign of x1 with respect to x2, element-wise using np.copysign()
print("\nSign of x1 to that of x2, element-wise:")
print(np.copysign(x1, x2)) 

Original array: 
[-1  0  1  2]

Sign of x1 to that of x2, element-wise:
[-1. -0. -1. -2.]


In [26]:
# Creating an array containing integers 0, 1, and -1
x = np.array([0, 1, -1])

# Displaying the original array x
print("Original array: ")
print(x)

# Calculating the numerical negative value of each element in array x using np.negative()
r1 = np.negative(x)

# Calculating the numerical negative value of each element in array x using the unary minus operator
r2 = -x

# Checking if the results from np.negative() and the unary minus operator are equal using np.array_equal()
assert np.array_equal(r1, r2)

# Displaying the numerical negative value for all elements of the array obtained using np.negative()
print("Numerical negative value for all elements of the said array:")
print(r1) 

Original array: 
[ 0  1 -1]
Numerical negative value for all elements of the said array:
[ 0 -1  1]


In [27]:
# Creating an array containing floating-point numbers
x = np.array([1., 2., .2, .3])

# Displaying the original array x
print("Original array: ")
print(x)

# Calculating the reciprocal of each element in array x using np.reciprocal()
r1 = np.reciprocal(x)

# Calculating the reciprocal of each element in array x using the reciprocal operator (1/x)
r2 = 1/x

# Checking if the results from np.reciprocal() and the reciprocal operator are equal using np.array_equal()
assert np.array_equal(r1, r2)

# Displaying the reciprocals for all elements of the array obtained using np.reciprocal()
print("Reciprocal for all elements of the said array:")
print(r1)

Original array: 
[1.  2.  0.2 0.3]
Reciprocal for all elements of the said array:
[1.         0.5        5.         3.33333333]


In [28]:
# Creating two arrays x and y
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])

# Displaying the first array x
print("Array1: ")
print(x)

# Displaying the second array y
print("Array1: ")
print(y)

# Calculating the power of elements in array x raised to the power of elements in array y
r1 = np.power(x, y)

# Displaying the result of x raised to the power of y
print("Result- x^y:")
print(r1) 

Array1: 
[[1 2]
 [3 4]]
Array1: 
[[1 2]
 [1 2]]
Result- x^y:
[[ 1  4]
 [ 3 16]]


In [29]:
# Creating an array x
x = np.array([1, 3, 5, 0, -1, -7, 0, 5])

# Displaying the original array x
print("Original array;")
print(x)

# Using np.sign() to find the sign of each element in array x
r1 = np.sign(x)

# Creating a copy of array x and modifying it to assign signs manually
r2 = np.copy(x)
r2[r2 > 0] = 1  # If element is positive, set it to 1
r2[r2 < 0] = -1  # If element is negative, set it to -1

# Comparing the results obtained from np.sign() and manually assigning signs
assert np.array_equal(r1, r2)

# Displaying the element-wise indication of the sign for all elements of the array using np.sign()
print("Element-wise indication of the sign for all elements of the said array:")
print(r1)

Original array;
[ 1  3  5  0 -1 -7  0  5]
Element-wise indication of the sign for all elements of the said array:
[ 1  1  1  0 -1 -1  0  1]
