In [1]:
import numpy as np

In [2]:
# Create a large NumPy array with 1 million elements
large_array = np.random.rand(1_000_000)

# Function to calculate the standard deviation using a for loop
def std_dev_using_loop(array):
    mean = np.mean(array)
    variance = 0.0
    for element in array:
        variance += (element - mean) ** 2
    variance /= len(array)
    return np.sqrt(variance)

# Calculate the standard deviation using the for loop
std_loop = std_dev_using_loop(large_array)
print("Standard deviation using for loop:", std_loop)



Standard deviation using for loop: 0.2887271915863127


In [3]:
# Optimize the standard deviation calculation using NumPy's built-in function
std_numpy = np.std(large_array)
print("Standard deviation using NumPy's built-in function:", std_numpy)

Standard deviation using NumPy's built-in function: 0.2887271915863172


In [4]:
# Create a large 2D NumPy array with shape (1000, 1000)
large_array = np.random.rand(1000, 1000)

# Function to transpose a 2D array using nested for loops
def transpose_using_loops(array):
    rows, cols = array.shape
    transposed_array = np.zeros((cols, rows))
    for i in range(rows):
        for j in range(cols):
            transposed_array[j, i] = array[i, j]
    return transposed_array

# Transpose the array using the nested for loops
transposed_loop = transpose_using_loops(large_array)
print("Transposed array using for loop (first 5x5 block):\n", transposed_loop[:5, :5])

Transposed array using for loop (first 5x5 block):
 [[0.23903337 0.19007353 0.85859229 0.28750725 0.35557048]
 [0.98251248 0.90925071 0.1161072  0.13561969 0.74814477]
 [0.43103037 0.72191547 0.30839426 0.3684516  0.48460447]
 [0.37271006 0.03125132 0.43701681 0.03482462 0.26708755]
 [0.16753644 0.50204953 0.03975582 0.51152274 0.97186594]]


In [5]:
# Optimize the transposition using NumPy's transpose() function
transposed_numpy = np.transpose(large_array)
print("Transposed array using NumPy's transpose() function (first 5x5 block):\n", transposed_numpy[:5, :5])

Transposed array using NumPy's transpose() function (first 5x5 block):
 [[0.23903337 0.19007353 0.85859229 0.28750725 0.35557048]
 [0.98251248 0.90925071 0.1161072  0.13561969 0.74814477]
 [0.43103037 0.72191547 0.30839426 0.3684516  0.48460447]
 [0.37271006 0.03125132 0.43701681 0.03482462 0.26708755]
 [0.16753644 0.50204953 0.03975582 0.51152274 0.97186594]]


In [6]:
# Create two large 2D NumPy arrays with shape (1000, 1000)
array1 = np.random.rand(1000, 1000)
array2 = np.random.rand(1000, 1000)

# Function to compute element-wise multiplication using nested for loops
def elementwise_multiplication_using_loops(arr1, arr2):
    rows, cols = arr1.shape
    result = np.zeros((rows, cols))
    for i in range(rows):
        for j in range(cols):
            result[i, j] = arr1[i, j] * arr2[i, j]
    return result

# Compute the element-wise multiplication using the nested for loops
result_loop = elementwise_multiplication_using_loops(array1, array2)
print("Element-wise multiplication using for loop (first 5x5 block):\n", result_loop[:5, :5])

Element-wise multiplication using for loop (first 5x5 block):
 [[0.22136729 0.10063924 0.30866945 0.34007099 0.26016479]
 [0.32494352 0.00306148 0.49284438 0.02764902 0.05744921]
 [0.22614241 0.17308528 0.16583555 0.07813882 0.02567455]
 [0.01512018 0.06191294 0.50053005 0.34182763 0.19508571]
 [0.07593631 0.12350505 0.09011245 0.06890292 0.43955031]]


In [7]:
# Optimize the element-wise multiplication using NumPy's vectorized operations
result_vectorized = array1 * array2
print("Element-wise multiplication using vectorized operations (first 5x5 block):\n", result_vectorized[:5, :5])

Element-wise multiplication using vectorized operations (first 5x5 block):
 [[0.22136729 0.10063924 0.30866945 0.34007099 0.26016479]
 [0.32494352 0.00306148 0.49284438 0.02764902 0.05744921]
 [0.22614241 0.17308528 0.16583555 0.07813882 0.02567455]
 [0.01512018 0.06191294 0.50053005 0.34182763 0.19508571]
 [0.07593631 0.12350505 0.09011245 0.06890292 0.43955031]]


In [8]:
# Create a large 3D NumPy array with shape (100, 100, 100)
large_array = np.random.rand(100, 100, 100)

# Function to compute the sum of all elements using nested for loops
def sum_using_loops(array):
    total_sum = 0.0
    for i in range(array.shape[0]):
        for j in range(array.shape[1]):
            for k in range(array.shape[2]):
                total_sum += array[i, j, k]
    return total_sum

# Compute the sum using the nested for loops
sum_loop = sum_using_loops(large_array)
print("Sum using nested for loops:", sum_loop)

# Optimize the sum computation using NumPy's built-in function
sum_numpy = np.sum(large_array)
print("Sum using NumPy's built-in function:", sum_numpy)

Sum using nested for loops: 500355.56749845983
Sum using NumPy's built-in function: 500355.5674984588


In [9]:
# Generate a large NumPy array with random integers
large_array = np.random.randint(1, 1000000, size=1000000)

# Function to find the maximum element using a for loop
def find_max_with_loop(arr):
    max_element = arr[0]
    for element in arr:
        if element > max_element:
            max_element = element
    return max_element

# Find the maximum element using the for loop method
max_with_loop = find_max_with_loop(large_array)

# Find the maximum element using NumPy's built-in function
max_with_numpy = np.max(large_array)

# Display the results
print(f"Maximum element using for loop: {max_with_loop}")
print(f"Maximum element using NumPy: {max_with_numpy}")

Maximum element using for loop: 999994
Maximum element using NumPy: 999994


In [10]:
# Generate two large 1D NumPy arrays with random integers
array1 = np.random.randint(1, 1000, size=1000000)
array2 = np.random.randint(1, 1000, size=1000000)

# Function to compute element-wise division using a for loop
def element_wise_division_with_loop(arr1, arr2):
    result = np.empty_like(arr1, dtype=float)
    for i in range(len(arr1)):
        result[i] = arr1[i] / arr2[i]
    return result

# Compute element-wise division using the for loop method
result_with_loop = element_wise_division_with_loop(array1, array2)

# Compute element-wise division using NumPy's vectorized operations
result_with_numpy = array1 / array2

# Display first 10 results to verify
print("First 10 results using for loop:")
print(result_with_loop[:10])

print("First 10 results using NumPy:")
print(result_with_numpy[:10])

First 10 results using for loop:
[2.06493506 0.2        1.17928903 0.36486486 0.27272727 7.66666667
 2.38132296 6.18300654 0.83351709 1.38330171]
First 10 results using NumPy:
[2.06493506 0.2        1.17928903 0.36486486 0.27272727 7.66666667
 2.38132296 6.18300654 0.83351709 1.38330171]
