In [1]:
# Importing the necessary NumPy library
import numpy as np

# Create a 4x4 array with random values
array = np.random.rand(4, 4)

# Extract the upper triangular part of the matrix
upper_triangular = np.triu(array)

# Printing the original array and its upper triangular part
print("4x4 Array:\n", array)
print("Upper Triangular Part of the Array:\n", upper_triangular)


4x4 Array:
 [[0.42920679 0.46162148 0.03825132 0.14867221]
 [0.00522182 0.79561561 0.86933733 0.04877585]
 [0.96287645 0.34918462 0.11281321 0.2151617 ]
 [0.70575894 0.74653889 0.45277592 0.96622739]]
Upper Triangular Part of the Array:
 [[0.42920679 0.46162148 0.03825132 0.14867221]
 [0.         0.79561561 0.86933733 0.04877585]
 [0.         0.         0.11281321 0.2151617 ]
 [0.         0.         0.         0.96622739]]
