In [1]:
import numpy as np  # Import NumPy library
from scipy.linalg import qr, lu, cholesky  # Import linear algebra decomposition functions from SciPy

In [2]:
# Create a matrix using NumPy
matrix = np.array([
    [4, 12, -16],
    [12, 37, -43],
    [-16, -43, 98]
])

# Apply QR decomposition
Q, R = qr(matrix)

# Apply LU decomposition
P, L, U = lu(matrix)

# Apply Cholesky decomposition
# Ensure the matrix is positive-definite for Cholesky decomposition
cholesky_matrix = np.array([
    [4, 12, -16],
    [12, 37, -43],
    [-16, -43, 98]
])
L_cholesky = cholesky(cholesky_matrix, lower=True)

# Print the original matrix and the decomposition results
print("Original Matrix:")
print(matrix)

print("\nQR Decomposition:")
print("Q matrix:")
print(Q)
print("R matrix:")
print(R)

print("\nLU Decomposition:")
print("P matrix:")
print(P)
print("L matrix:")
print(L)
print("U matrix:")
print(U)

print("\nCholesky Decomposition:")
print("L matrix:")
print(L_cholesky)

Original Matrix:
[[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]

QR Decomposition:
Q matrix:
[[-0.19611614 -0.16947544  0.96582428]
 [-0.58834841 -0.76762404 -0.25416428]
 [ 0.78446454 -0.61808689  0.05083286]]
R matrix:
[[-20.39607805 -57.85425987 105.31436457]
 [  0.          -3.8580585  -24.85307452]
 [  0.           0.           0.45749571]]

LU Decomposition:
P matrix:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L matrix:
[[ 1.          0.          0.        ]
 [-0.75        1.          0.        ]
 [-0.25        0.26315789  1.        ]]
U matrix:
[[-16.         -43.          98.        ]
 [  0.           4.75        30.5       ]
 [  0.           0.           0.47368421]]

Cholesky Decomposition:
L matrix:
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
