In [1]:
import numpy as np

In [2]:
x = np.random.normal(size=5)
x

array([-0.24215678, -0.75116364, -0.51649643, -0.20967739, -0.86720851])

In [3]:
x = np.random.randint(low=10, high=30, size=6)
x

array([10, 17, 27, 27, 18, 23])

In [4]:
x = np.random.random((3, 3, 3))
x

array([[[0.43448303, 0.20085107, 0.81050292],
        [0.03539614, 0.77773611, 0.77299529],
        [0.08793194, 0.80719847, 0.24979632]],

       [[0.11778996, 0.6087    , 0.82493715],
        [0.72805492, 0.74339078, 0.26901695],
        [0.07807914, 0.57988834, 0.28108955]],

       [[0.59178664, 0.93104168, 0.03465077],
        [0.86491081, 0.57598145, 0.63653459],
        [0.25414166, 0.50713358, 0.27283533]]])

In [5]:
x = np.random.random((5, 5))
x

array([[0.95873202, 0.49057908, 0.45467637, 0.68371487, 0.87148499],
       [0.29027881, 0.97692938, 0.0340384 , 0.17605019, 0.30581964],
       [0.93910407, 0.74992589, 0.98513868, 0.59372969, 0.59415946],
       [0.20892054, 0.10728292, 0.15146022, 0.4375073 , 0.92772701],
       [0.56530808, 0.91962263, 0.58089939, 0.88514968, 0.88159723]])

In [6]:
xmin, xmax = x.min(), x.max()
xmin, xmax

(0.03403839578205148, 0.9851386791991346)

In [7]:
x = np.random.rand(10, 4)
x

array([[0.93145039, 0.57473716, 0.40304734, 0.14075913],
       [0.59131857, 0.4337145 , 0.59297821, 0.21776156],
       [0.95880974, 0.23595712, 0.76322948, 0.6600897 ],
       [0.05502495, 0.47649128, 0.55600143, 0.64452512],
       [0.2096716 , 0.22836698, 0.06495614, 0.76100834],
       [0.2937352 , 0.48034691, 0.2644657 , 0.0525839 ],
       [0.00342349, 0.91137618, 0.83768662, 0.85532917],
       [0.02310388, 0.88129476, 0.60877698, 0.09415729],
       [0.90639437, 0.02968482, 0.52950902, 0.50022009],
       [0.68085203, 0.05954365, 0.47641008, 0.17107206]])

In [8]:
y = x[:5, :]
y

array([[0.93145039, 0.57473716, 0.40304734, 0.14075913],
       [0.59131857, 0.4337145 , 0.59297821, 0.21776156],
       [0.95880974, 0.23595712, 0.76322948, 0.6600897 ],
       [0.05502495, 0.47649128, 0.55600143, 0.64452512],
       [0.2096716 , 0.22836698, 0.06495614, 0.76100834]])

In [9]:
x = np.arange(10)
np.random.shuffle(x)
x

array([0, 9, 8, 6, 2, 3, 5, 4, 1, 7])

In [10]:
np.random.permutation(10)

array([5, 0, 9, 4, 8, 1, 6, 3, 2, 7])

In [12]:
x = np.random.random((3, 3))
x

array([[0.19172179, 0.49155334, 0.83337846],
       [0.54416286, 0.18275379, 0.3855864 ],
       [0.94782969, 0.74533586, 0.40950365]])

In [13]:
xmax, xmin = x.max(), x.min()


In [14]:
x = (x - xmin)/(xmax - xmin)
x

array([[0.01172171, 0.40361949, 0.85040539],
       [0.47238329, 0.        , 0.26511436],
       [1.        , 0.73532844, 0.29637564]])

In [15]:
x = np.random.random(10)
x

array([0.06527837, 0.78741564, 0.93606094, 0.79971582, 0.28654955,
       0.33936167, 0.63626534, 0.67515478, 0.38030187, 0.69177288])

In [16]:
x.sort()
x

array([0.06527837, 0.28654955, 0.33936167, 0.38030187, 0.63626534,
       0.67515478, 0.69177288, 0.78741564, 0.79971582, 0.93606094])

In [17]:
# Generating an array of 5 random numbers between 1 and 12 using np.random.uniform()
x = np.random.uniform(1, 12, 5)

# Setting a value 'v' to find the number closest to it in the array 'x'
v = 4

# Finding the value 'n' in 'x' that is closest to 'v'
# Using np.abs(x - v).argmin() to get the index of the element in 'x' closest to 'v'
# Accessing the element using x.flat[index] to get the closest value 'n'
n = x.flat[np.abs(x - v).argmin()]

# Printing the value 'n' that is closest to 'v'
print(n)

2.9358539321728534


In [18]:
# Generating the first array 'x' with 6 random integers (0 or 1) using np.random.randint()
x = np.random.randint(0, 2, 6)

# Printing the first generated array 'x'
print("First array:")
print(x)

# Generating the second array 'y' with 6 random integers (0 or 1) using np.random.randint()
y = np.random.randint(0, 2, 6)

# Printing the second generated array 'y'
print("Second array:")
print(y)

# Checking if the two arrays 'x' and 'y' are equal using np.allclose()
# This function returns True if the two arrays are element-wise equal within a tolerance
array_equal = np.allclose(x, y)

# Printing whether the two arrays are equal or not
print("Test above two arrays are equal or not!")
print(array_equal) 

First array:
[0 0 1 1 1 0]
Second array:
[1 0 0 0 0 0]
Test above two arrays are equal or not!
False


In [19]:
# Generating an array 'x' with 15 random floats between 0 and 1 using np.random.random()
x = np.random.random(15)

# Displaying the original array 'x'
print("Original array:")
print(x)

# Finding the index of the maximum value in the array using x.argmax()
# Replacing the maximum value with -1 using the index obtained from x.argmax()
x[x.argmax()] = -1

# Displaying the modified array where the maximum value has been replaced by -1
print("Maximum value replaced by -1:")
print(x) 

Original array:
[0.6673103  0.59568549 0.86377677 0.14060165 0.85431536 0.96454091
 0.64914464 0.09354117 0.41013266 0.07707562 0.43169887 0.81496882
 0.98492742 0.72498201 0.13007987]
Maximum value replaced by -1:
[ 0.6673103   0.59568549  0.86377677  0.14060165  0.85431536  0.96454091
  0.64914464  0.09354117  0.41013266  0.07707562  0.43169887  0.81496882
 -1.          0.72498201  0.13007987]


In [20]:
# Generating a 10x2 array 'a' with random values between 0 and 1 using np.random.random()
a = np.random.random((10, 2))

# Extracting x and y coordinates from the array 'a' using np.atleast_2d() method
# at least 2-dimensional arrays from the columns of 'a'
x, y = np.atleast_2d(a[:, 0], a[:, 1])

# Calculating the Euclidean distance between points in the 'a' array using the formula:
# d = sqrt((x - x_transpose)^2 + (y - y_transpose)^2)
# where x and y are the coordinate matrices created, and T is the transpose of those matrices
d = np.sqrt((x - x.T) ** 2 + (y - y.T) ** 2)

# Displaying the resultant matrix containing the distances between points
print(d) 

[[0.         0.25283536 0.07168813 0.38863211 0.123468   0.54460039
  0.10030383 0.4533992  0.72895311 0.60451983]
 [0.25283536 0.         0.2476979  0.18225933 0.27260904 0.38724665
  0.23052998 0.37183754 0.50999264 0.53130597]
 [0.07168813 0.2476979  0.         0.4073413  0.05334645 0.48974988
  0.03364809 0.5048561  0.7475132  0.5361626 ]
 [0.38863211 0.18225933 0.4073413  0.         0.44246873 0.50211065
  0.39813131 0.24519135 0.34094475 0.68125311]
 [0.123468   0.27260904 0.05334645 0.44246873 0.         0.46628739
  0.04473729 0.5544003  0.78008962 0.49460907]
 [0.54460039 0.38724665 0.48974988 0.50211065 0.46628739 0.
  0.45621203 0.73961689 0.69913621 0.21856543]
 [0.10030383 0.23052998 0.03364809 0.39813131 0.04473729 0.45621203
  0.         0.51208529 0.73637199 0.50458623]
 [0.4533992  0.37183754 0.5048561  0.24519135 0.5544003  0.73961689
  0.51208529 0.         0.40915405 0.90226494]
 [0.72895311 0.50999264 0.7475132  0.34094475 0.78008962 0.69913621
  0.73637199 0.40915

In [21]:
# Generating a random array 'x' with integers between 0 and 10 (exclusive) having 40 elements
x = np.random.randint(0, 10, 40)

# Displaying the original array 'x'
print("Original array:")
print(x)

# Finding the most frequent value in the array using np.bincount() to count occurrences
# Then using argmax() to find the index of the maximum count, which represents the most frequent value
most_frequent_value = np.bincount(x).argmax()

# Displaying the most frequent value in the array
print("Most frequent value in the above array:")
print(most_frequent_value)

Original array:
[1 7 1 2 4 9 5 4 4 8 5 0 0 1 6 7 7 2 7 1 7 9 3 3 4 0 7 6 6 8 2 4 4 0 6 5 2
 4 8 9]
Most frequent value in the above array:
4


In [22]:
# Generating a random 10x2 array 'z' with random numbers between 0 and 1
z = np.random.random((10, 2))

# Extracting the first column as 'x' and the second column as 'y' from the array 'z'
x, y = z[:, 0], z[:, 1]

# Calculating the Euclidean distance (r) using the formula sqrt(x^2 + y^2)
r = np.sqrt(x**2 + y**2)

# Calculating the angles (t) using arctan2() function, which returns the arctangent of y/x in radians
t = np.arctan2(y, x)

# Displaying the calculated Euclidean distances (r)
print(r)

# Displaying the calculated angles (t) in radians
print(t)

[0.46258943 0.5189364  0.24422192 0.73671905 1.06310028 1.24969282
 0.9022769  1.15852525 0.24801942 0.8072304 ]
[0.22778454 0.96605738 1.50535713 1.36972879 0.96530861 0.81350604
 0.45877781 1.01833852 0.73776655 0.28816239]


In [23]:
x = np.arange(100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
a = np.random.uniform(0, 100)
a

19.089628896209344

In [25]:
index = (np.abs(x-a)).argmin()

In [26]:
x[index]

19

In [27]:
x =np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.random.shuffle(x)

In [29]:
n = 1
x[np.argsort(x)[-n:]]

array([9])

In [30]:
# Setting the random seed to 32 for reproducibility
np.random.seed(32)

# Generating a 3D NumPy array 'nums' with dimensions 300x400x5
# Filling it with random integers in the range [0, 256) and data type uint8
nums = np.random.randint(low=0, high=256, size=(300, 400, 5), dtype=np.uint8)

# Printing the generated array 'nums'
print(nums)

[[[215  42 224 219  43]
  [166  69  15 133 255]
  [105  95  54  37 201]
  ...
  [240  22  66 232 132]
  [ 13  85  53 220 170]
  [249  62 221 146  69]]

 [[ 73  79 148 132 164]
  [  3  93  98 138 200]
  [174  34  31 208 130]
  ...
  [ 15 252  41  64  39]
  [188 216 223 124  27]
  [ 85 112 240 116 231]]

 [[227  50 243  20 171]
  [ 12  66 108 102  63]
  [107  54   0   0 173]
  ...
  [215  46  57  99 151]
  [243 199  31  28 179]
  [143   7  30 175 190]]

 ...

 [[214  64  64 212  62]
  [140  44 217  17 164]
  [226 146 247  53 199]
  ...
  [189  68  49 117  63]
  [ 14  17 109  82  92]
  [155 221 135 184 231]]

 [[132 194 160 136 102]
  [132 244 230 117 181]
  [146 245  21 164  29]
  ...
  [125 240 243 190 240]
  [137  41 157 117 155]
  [ 20  92  72 182  41]]

 [[120  45 198 218 190]
  [ 42 150 190 103 106]
  [164  71 220 114  59]
  ...
  [143  20 219 154  85]
  [219 190 170 227 246]
  [ 39  14 127 230 158]]]
