In [1]:
import numpy as np

In [7]:
import pandas as pd

In [2]:
# Initialize a Python list
python_list = [1, 2, 3, 4, 5]
print("Original array:", python_list)
print("Type:", type(python_list))

Original array: [1, 2, 3, 4, 5]
Type: <class 'list'>


In [3]:
# Convert the Python list to a numpy array
numpy_array = np.array(python_list)
print("Print list to a numpy array:")

# Print the NumPy array
print(numpy_array)
print("Type:", type(numpy_array))

Print list to a numpy array:
[1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [4]:
# Initialize a NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])
print("Original NumPy array:", numpy_array)
print("Type:", type(numpy_array))

# Convert the NumPy array to a Python list 
python_list = numpy_array.tolist()
print("\nNumpy array to a Python list:")

# Print the Python list
print(python_list)
print("Type:", type(python_list))

Original NumPy array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>

Numpy array to a Python list:
[1, 2, 3, 4, 5]
Type: <class 'list'>


In [5]:
# Initialize a Python tuple
python_tuple = (1, 2, 3, 4, 5)
print("Original Python tuple:", python_tuple)
print("Type", type(python_tuple))

# Convert the Python tuple to a NumPy array
numpy_array = np.array(python_tuple)
print("\nPython tuple to a NumPy array:")

# Print the NumPy array
print(numpy_array)
print("Type:", type(numpy_array))

Original Python tuple: (1, 2, 3, 4, 5)
Type <class 'tuple'>

Python tuple to a NumPy array:
[1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [6]:
# Initialize a NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])
print("Original NumPy array:", numpy_array)
print("Type:", type(numpy_array))

# Convert the NumPy array to a Python tuple
python_tuple = tuple(numpy_array)

print("\nNumPy array to a Python tuple:")
# Print the Python tuple
print(python_tuple)
print("Type:", type(python_tuple))

Original NumPy array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>

NumPy array to a Python tuple:
(1, 2, 3, 4, 5)
Type: <class 'tuple'>


In [8]:
# Initialize a Pandas DataFrame
data = {'A': [1, 2, 3, 4, 5],
        'B': [10, 20, 30, 40, 50],
        'C': [100, 200, 300, 400, 500]}
df = pd.DataFrame(data)

print("Original Pandas DataFrame:", df)
print("Type:", type(df))
 
# Convert the Pandas DataFrame to a NumPy array
numpy_array = df.to_numpy()
print("\nPandas DataFrame to a NumPy array:")
# Print the NumPy array
print(numpy_array)
print("Type:", type(numpy_array))

Original Pandas DataFrame:    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500
Type: <class 'pandas.core.frame.DataFrame'>

Pandas DataFrame to a NumPy array:
[[  1  10 100]
 [  2  20 200]
 [  3  30 300]
 [  4  40 400]
 [  5  50 500]]
Type: <class 'numpy.ndarray'>


In [9]:
# Initialize a NumPy array
numpy_array = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print("Original NumPy array:", numpy_array)
print("Type:", type(numpy_array))

# Convert the Numpy array to a Pandas DataFrame
df = pd.DataFrame(numpy_array, columns=['Column1', 'Column2', 'Column3'])
print("\nNumPy array to a Pandas DataFrame")
# Print the Pandas DataFrame
print(df)
print(type(df))

Original NumPy array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type: <class 'numpy.ndarray'>

NumPy array to a Pandas DataFrame
   Column1  Column2  Column3
0        1        2        3
1        4        5        6
2        7        8        9
<class 'pandas.core.frame.DataFrame'>


In [11]:
# Initialize a dictionary with numeric values
data_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

print("Original dictionary with numeric values:",data_dict)
print("Type:",type(data_dict))

# Convert the dictionary values to a NumPy array
numpy_array = np.array(list(data_dict.values()))
print("\nDictionary values to a NumPy array")

# Print the NumPy array
print(numpy_array)
print(type(numpy_array))

Original dictionary with numeric values: {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
Type: <class 'dict'>

Dictionary values to a NumPy array
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
# Create a NumPy array
array = np.array([10, 20, 30, 40, 50])
print("Original NumPy array:",array)
print("Type:",type(array))

# Convert NumpPy array to dictionary with indices as keys and elements as values
array_dict = {index: value for index, value in enumerate(array)}
print("\nNumPy array to dictionary with indices as keys and elements as values:")
# Print the resulting dictionary 
print(array_dict)
print(type(array_dict))

Original NumPy array: [10 20 30 40 50]
Type: <class 'numpy.ndarray'>

NumPy array to dictionary with indices as keys and elements as values:
{0: 10, 1: 20, 2: 30, 3: 40, 4: 50}
<class 'dict'>


In [13]:
# Define a nested Python list
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("Original nested Python list:",nested_list)
print("Type:",type(nested_list))

# Convert the nested list to a 2D NumPy array
array_2d = np.array(nested_list)
print("\nNested list to a 2D NumPy array:")

# Print the 2D NumPy array
print(array_2d)
print("Type:",type(array_2d))

Original nested Python list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Type: <class 'list'>

Nested list to a 2D NumPy array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Type: <class 'numpy.ndarray'>


In [14]:
# Create a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original 2D NumPy array:",array_2d)
print("Type:",type(array_2d))

# Convert the 2D NumPy array to a nested Python list
nested_list = array_2d.tolist()
print("\n2D NumPy array to a nested Python list:")

# Print the nested Python list
print(nested_list)
print("Type:",type(nested_list))

Original 2D NumPy array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type: <class 'numpy.ndarray'>

2D NumPy array to a nested Python list:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Type: <class 'list'>
