In [1]:
import numpy as np

In [2]:
# Create a large 1D array with 1 million elements
large_array = np.random.rand(1_000_000)

# Function to calculate the sum using a for loop
def sum_using_loop(array):
    total = 0.0
    for element in array:
        total += element
    return total

# Calculate the sum using the for loop
sum_loop = sum_using_loop(large_array)
print("Sum using for loop:", sum_loop)

# Optimize the sum calculation using NumPy's built-in function
sum_numpy = np.sum(large_array)
print("Sum using NumPy's built-in function:", sum_numpy)

Sum using for loop: 499767.56993624166
Sum using NumPy's built-in function: 499767.5699362222


In [3]:
# Generate two large NumPy arrays with 1 million elements each
array1 = np.random.rand(1_000_000)
array2 = np.random.rand(1_000_000)

# Function to perform element-wise addition using a for loop
def add_using_loop(arr1, arr2):
    result = np.zeros_like(arr1)
    for i in range(len(arr1)):
        result[i] = arr1[i] + arr2[i]
    return result

# Perform element-wise addition using the for loop
sum_loop = add_using_loop(array1, array2)
print("Sum using for loop (first 10 elements):", sum_loop[:10])

# Optimize the element-wise addition using vectorized operations
sum_vectorized = array1 + array2
print("Sum using vectorized operations (first 10 elements):", sum_vectorized[:10])


Sum using for loop (first 10 elements): [0.43522632 0.59381731 0.68383718 1.28241075 1.19722884 1.17870847
 1.69564047 0.19936264 0.81946195 0.77812151]
Sum using vectorized operations (first 10 elements): [0.43522632 0.59381731 0.68383718 1.28241075 1.19722884 1.17870847
 1.69564047 0.19936264 0.81946195 0.77812151]


In [ ]:
# Generate two large 2D NumPy arrays with shape (1000, 1000)
array1 = np.random.rand(1000, 1000)
array2 = np.random.rand(1000, 1000)

# Function to compute the dot product using nested for loops
def dot_product_using_loops(arr1, arr2):
    result = np.zeros((arr1.shape[0], arr2.shape[1]))
    for i in range(arr1.shape[0]):
        for j in range(arr2.shape[1]):
            for k in range(arr1.shape[1]):
                result[i, j] += arr1[i, k] * arr2[k, j]
    return result

# Compute the dot product using the nested for loops
dot_product_loops = dot_product_using_loops(array1, array2)
print("Dot product using nested for loops (first 5x5 block):\n", dot_product_loops[:5, :5])

# this code definitely needs optimization
# run time exceeded
# thus, no output can be seen below.

In [7]:
# Optimize the dot product computation using NumPy's dot() function
dot_product_numpy = np.dot(array1, array2)
print("Dot product using NumPy's dot() function (first 5x5 block):\n", dot_product_numpy[:5, :5])

Dot product using NumPy's dot() function (first 5x5 block):
 [[250.8138586  248.70854944 243.35743054 244.35043007 239.15266257]
 [264.1999249  269.19131998 253.73015006 261.53807159 252.60448587]
 [249.33952654 249.42554133 239.72634485 247.58071302 241.42249836]
 [252.64998888 256.8086697  251.3359215  254.31203747 246.319851  ]
 [262.95907622 265.70352936 261.24357996 259.32753179 253.28896622]]


In [8]:
# Create a large 2D NumPy array with shape (10000, 100)
large_array = np.random.rand(10000, 100)

# Function to calculate the row-wise mean using a for loop
def row_wise_mean_using_loop(array):
    row_means = np.zeros(array.shape[0])
    for i in range(array.shape[0]):
        row_means[i] = np.mean(array[i, :])
    return row_means

# Calculate the row-wise mean using the for loop
mean_loop = row_wise_mean_using_loop(large_array)
print("Row-wise mean using for loop (first 10 rows):", mean_loop[:10])

# Optimize the row-wise mean calculation using vectorized operations
mean_vectorized = np.mean(large_array, axis=1)
print("Row-wise mean using vectorized operations (first 10 rows):", mean_vectorized[:10])


Row-wise mean using for loop (first 10 rows): [0.46470359 0.50512447 0.4599706  0.46464672 0.49996935 0.44899845
 0.53276454 0.53147782 0.49924803 0.47391731]
Row-wise mean using vectorized operations (first 10 rows): [0.46470359 0.50512447 0.4599706  0.46464672 0.49996935 0.44899845
 0.53276454 0.53147782 0.49924803 0.47391731]
