In [1]:
import numpy as np

In [2]:
# Create a regular NumPy array with some values
data = np.array([1, 2, np.nan, 4, 5, np.nan, 7, 8, 9, 10])

# Create a mask to specify which values to mask (eg., NaN values)
mask = np.isnan(data)

# Create a mask to specify which values to mask (e.g., NaN values)
mask = np.isnan(data)

# Create a masked array using the regular array and the mask
masked_array = np.ma.masked_array(data, mask=mask)

# Count the number of masked elements in the masked array
num_masked_elements = np.ma.count_masked(masked_array)

# Print the original array, the masked array, and the number of masked elements
print("Original Array:")
print(data)

print("\nMasked Array:")
print(masked_array)

print("\nNumber of Masked Elements:")
print(num_masked_elements)

Original Array:
[ 1.  2. nan  4.  5. nan  7.  8.  9. 10.]

Masked Array:
[1.0 2.0 -- 4.0 5.0 -- 7.0 8.0 9.0 10.0]

Number of Masked Elements:
2


In [3]:
# Create two regular NumPy arrays with some values
data1 = np.array([1, 2, np.nan, 4, 5])
data2 = np.array([5, np.nan, 2, 3, 1])

# Create masks to specify which values to mask (e.g., NaN values)
mask1 = np.isnan(data1)
mask2 = np.isnan(data2)

# Create masked arrays using the regular arrays and the masks
masked_array1 = np.ma.masked_array(data1, mask=mask1)
masked_array2 = np.ma.masked_array(data2, mask=mask2)

# Perform element-wise addition of the two masked arrays, maintaining the masks
result_array = np.ma.add(masked_array1, masked_array2)

# Print the original masked arrays and the resulting array
print("Masked Array 1:")
print(masked_array1)

print("\nMasked Array 2:")
print(masked_array2)

print("\nResulting Array after Element-wise Addition:")
print(result_array)

Masked Array 1:
[1.0 2.0 -- 4.0 5.0]

Masked Array 2:
[5.0 -- 2.0 3.0 1.0]

Resulting Array after Element-wise Addition:
[6.0 -- -- 7.0 6.0]


In [4]:
import numpy.ma as ma

In [5]:
# create a 2D NumPy array of shape (4, 4) with random integers
array_2d = np.random.randint(0, 10, size=(4, 4))

# Specify the row to mask
row_to_mask = 2

# Create a masked array from the 2D array and mask all values in the specified row
masked_array = ma.masked_array(array_2d, mask=np.zeros_like(array_2d, dtype=bool))
masked_array[row_to_mask] = ma.masked

# Print the original array and the masked array 
print('Original 2D array:\n', array_2d)
print('Masked array (with row {} masked):\n'.format(row_to_mask), masked_array)

Original 2D array:
 [[0 1 1 0]
 [7 3 8 9]
 [2 5 4 6]
 [1 7 1 1]]
Masked array (with row 2 masked):
 [[0 1 1 0]
 [7 3 8 9]
 [-- -- -- --]
 [1 7 1 1]]


In [6]:
# Create a 2D NumPy array of shape (4, 4) with random integers
array_2d = np.random.randint(0, 100, size=(4, 4))

# Define the condition to mask elements greater than 50
condition = array_2d > 50

# Create a masked array from the 2D array using the condition
masked_array = ma.masked_array(array_2d, mask=condition)

# Print the original array and the masked array
print('Original 2D array:\n', array_2d)
print('Masked array (elements > 50 are masked):\n', masked_array)

Original 2D array:
 [[29 52 54 16]
 [50 58 57 87]
 [97 47 37 31]
 [ 2  8 86 78]]
Masked array (elements > 50 are masked):
 [[29 -- -- 16]
 [50 -- -- --]
 [-- 47 37 31]
 [2 8 -- --]]


In [8]:
# Create a 2D NumPy array of shape (4, 4) with random integers
array_2d = np.random.randint(0, 100, size=(4, 4))

# Define the condition to mask elements greater than 50
condition = array_2d > 50

# Create a masked array from the 2D array using the condition
masked_array = ma.masked_array(array_2d, mask=condition)

# Find the maximum value in the masked array, ignoring the masked elements
max_value = masked_array.max()

# Print the original array and the masked array
print('Original 2D array:\n', array_2d)
print('Masked array (elements > 50 are masked):\n', masked_array)
print('Maximum value (ignoring masked elements):', max_value)

Original 2D array:
 [[72 26 74 55]
 [74 76 28 16]
 [98 93 97 10]
 [81 82 55 33]]
Masked array (elements > 50 are masked):
 [[-- 26 -- --]
 [-- -- 28 16]
 [-- -- -- 10]
 [-- -- -- 33]]
Maximum value (ignoring masked elements): 33


In [9]:
# Create a 2D NumPy array of shape (4, 4) with random integers
array_2d = np.random.randint(0, 100, size=(4, 4))

# Define the condition to mask elements greater than 50
condition = array_2d > 50

# Create a masked array from the 2D array using the condition
masked_array = ma.masked_array(array_2d, mask=condition)

# Find the indices of all unmasked elements
unmasked_indices = np.where(~masked_array.mask)

# Print the original array, the masked array, and the indices of unmasked elements
print('Original 2D array:\n', array_2d)
print('Masked array (elements > 50 are masked):\n', masked_array)
print('Indices of all unmasked elements:\n', unmasked_indices)

Original 2D array:
 [[59 25 29  2]
 [27 96 39  5]
 [70 39  5 73]
 [61 52  3 78]]
Masked array (elements > 50 are masked):
 [[-- 25 29 2]
 [27 -- 39 5]
 [-- 39 5 --]
 [-- -- 3 --]]
Indices of all unmasked elements:
 (array([0, 0, 0, 1, 1, 1, 2, 2, 3], dtype=int64), array([1, 2, 3, 0, 2, 3, 1, 2, 2], dtype=int64))


In [10]:
# Create a 2D NumPy array of shape (4, 4) with random integers
array_2d = np.random.randint(0, 100, size=(4, 4)).astype(float)

# Define the condition to mask elements greater than 50
condition = array_2d > 50

# Create a masked array from the 2D array using the condition
masked_array = ma.masked_array(array_2d, mask=condition)

# Convert the masked array back to a regular NumPy array, replacing masked values with NaN
regular_array_with_nan = masked_array.filled(np.nan)

# Print the original array, the masked array, and the converted array
print('Original 2D array:\n', array_2d)
print('Masked array (elements > 50 are masked):\n', masked_array)
print('Converted array with NaN for masked values:\n', regular_array_with_nan)

Original 2D array:
 [[31. 89. 13. 30.]
 [77. 38. 79. 49.]
 [32. 78. 80. 46.]
 [26. 21. 47. 56.]]
Masked array (elements > 50 are masked):
 [[31.0 -- 13.0 30.0]
 [-- 38.0 -- 49.0]
 [32.0 -- -- 46.0]
 [26.0 21.0 47.0 --]]
Converted array with NaN for masked values:
 [[31. nan 13. 30.]
 [nan 38. nan 49.]
 [32. nan nan 46.]
 [26. 21. 47. nan]]


In [11]:
# Create a 2D NumPy array of shape (4, 4) with random integers
array_2d = np.random.randint(0, 100, size=(4, 4))

# Define the condition to mask elements greater than 50
condition = array_2d > 50

# Create a masked array from the 2D array using the condition
masked_array = ma.masked_array(array_2d, mask=condition)

# Create another 2D NumPy array of the same shape with random integers
multiplier_array = np.random.randint(1, 10, size=(4, 4))

# Perform masked multiplication
masked_multiplication_result = masked_array * multiplier_array

# Print the original arrays and the masked multiplication result
print('Original 2D array:\n', array_2d)
print('Masked array (elements > 50 are masked):\n', masked_array)
print('Multiplier array:\n', multiplier_array)
print('Masked multiplication result:\n', masked_multiplication_result)

Original 2D array:
 [[ 8 70 32  2]
 [36 40 39 64]
 [24 34 47 55]
 [14 88 87 38]]
Masked array (elements > 50 are masked):
 [[8 -- 32 2]
 [36 40 39 --]
 [24 34 47 --]
 [14 -- -- 38]]
Multiplier array:
 [[5 6 7 8]
 [3 8 2 6]
 [5 1 1 9]
 [4 7 8 5]]
Masked multiplication result:
 [[40 -- 224 16]
 [108 320 78 --]
 [120 34 47 --]
 [56 -- -- 190]]


In [12]:
# Create a 2D NumPy array of shape (4, 4) with random integers
array_2d = np.random.randint(0, 100, size=(4, 4))

# Define the condition to mask elements greater than 50
condition = array_2d > 50

# Create a masked array from the 2D array using the condition
masked_array = ma.masked_array(array_2d, mask=condition)

# Define a custom function to apply to the unmasked elements
def custom_function(x):
    return x * 2

# Apply the custom function only to the unmasked elements
unmasked_result = ma.apply_along_axis(custom_function, -1, masked_array)

# Print the original array, the masked array, and the result after applying the custom function
print('Original 2D array:\n', array_2d)
print('Masked array (elements > 50 are masked):\n', masked_array)
print('Result after applying custom function to unmasked elements:\n', unmasked_result)

Original 2D array:
 [[36 84 91 46]
 [32  6 93 71]
 [13 96 59 42]
 [ 4 94 47 24]]
Masked array (elements > 50 are masked):
 [[36 -- -- 46]
 [32 6 -- --]
 [13 -- -- 42]
 [4 -- 47 24]]
Result after applying custom function to unmasked elements:
 [[72 -- -- 92]
 [64 12 -- --]
 [26 -- -- 84]
 [8 -- 94 48]]


In [13]:
# Create a 2D NumPy array of shape (4, 4) with random integers
array_2d = np.random.randint(0, 100, size=(4, 4))

# Define the condition to mask elements greater than 50
condition = array_2d > 50

# Create a masked array from the 2D array using the condition
masked_array = ma.masked_array(array_2d, mask=condition)

# Extract the unmasked data as a regular NumPy array
unmasked_data = masked_array.compressed()

# Print the original array, the masked array, and the unmasked data
print('Original 2D array:\n', array_2d)
print('Masked array (elements > 50 are masked):\n', masked_array)
print('Unmasked data extracted as a regular NumPy array:\n', unmasked_data)

Original 2D array:
 [[74 59 10 11]
 [92 71 67 48]
 [16 45 49 15]
 [92 55 22 94]]
Masked array (elements > 50 are masked):
 [[-- -- 10 11]
 [-- -- -- 48]
 [16 45 49 15]
 [-- -- 22 --]]
Unmasked data extracted as a regular NumPy array:
 [10 11 48 16 45 49 15 22]


In [14]:
# Create a 2D NumPy array of shape (4, 4) with random integers
array_2d = np.random.randint(0, 100, size=(4, 4))

# Define the condition to mask elements greater than 50
condition = array_2d > 50

# Create a masked array from the 2D array using the condition
masked_array = ma.masked_array(array_2d, mask=condition)

# Perform a masked sum operation, ignoring the masked elements
masked_sum = masked_array.sum()

# Print the original array, the masked array, and the result of the masked sum
print('Original 2D array:\n', array_2d)
print('Masked array (elements > 50 are masked):\n', masked_array)
print('Sum of unmasked elements:', masked_sum)

Original 2D array:
 [[72  1 32 20]
 [26 46 94 97]
 [15 87 28 35]
 [42 32 30  0]]
Masked array (elements > 50 are masked):
 [[-- 1 32 20]
 [26 46 -- --]
 [15 -- 28 35]
 [42 32 30 0]]
Sum of unmasked elements: 307


In [15]:
# Create a 2D NumPy array of shape (5, 5) with random integers
array_2d = np.random.randint(0, 100, size=(5, 5))

# Define a complex condition to mask elements: values less than 20 or greater than 80
condition = (array_2d < 20) | (array_2d > 80)

# Create a masked array from the 2D array using the complex condition
masked_array = ma.masked_array(array_2d, mask=condition)

# Print the original array and the masked array
print('Original 2D array:\n', array_2d)
print('Masked array (values < 20 or > 80 are masked):\n', masked_array)

Original 2D array:
 [[42 68 33 14 26]
 [ 6 50 13 10 70]
 [57 33 68 81 97]
 [92 47 37 50 25]
 [84 74 26 68 62]]
Masked array (values < 20 or > 80 are masked):
 [[42 68 33 -- 26]
 [-- 50 -- -- 70]
 [57 33 68 -- --]
 [-- 47 37 50 25]
 [-- 74 26 68 62]]


In [16]:
# Create a 2D NumPy array of shape (5, 5) with random integers
array_2d = np.random.randint(0, 100, size=(5, 5))

# Define an initial condition to mask elements less than 20
initial_condition = array_2d < 20

# Create a masked array from the 2D array using the initial condition
masked_array = ma.masked_array(array_2d, mask=initial_condition)

# Define an additional condition to mask elements greater than 80
additional_condition = array_2d > 80

# Update the mask to include additional elements
masked_array.mask = masked_array.mask | additional_condition

# Print the original array, the initial masked array, and the updated masked array
print('Original 2D array:\n', array_2d)
print('Initial masked array (values < 20 are masked):\n', masked_array)
print('Updated masked array (values < 20 or > 80 are masked):\n', masked_array)

Original 2D array:
 [[47 81 79 67 48]
 [25 78 98 90 95]
 [94 84 69 59 50]
 [95 48 86 34 80]
 [35 81 81 92 44]]
Initial masked array (values < 20 are masked):
 [[47 -- 79 67 48]
 [25 78 -- -- --]
 [-- -- 69 59 50]
 [-- 48 -- 34 80]
 [35 -- -- -- 44]]
Updated masked array (values < 20 or > 80 are masked):
 [[47 -- 79 67 48]
 [25 78 -- -- --]
 [-- -- 69 59 50]
 [-- 48 -- 34 80]
 [35 -- -- -- 44]]


In [17]:
# Create a 2D NumPy array of shape (5, 5) with random integers
array_2d = np.random.randint(0, 100, size=(5, 5))

# Define a condition to mask elements less than 20
condition = array_2d < 20

# Create a masked array from the 2D array using the condition
masked_array = ma.masked_array(array_2d, mask=condition)

# Apply the sin function only to the unmasked elements
result_array = ma.sin(masked_array)

# Print the original array, the masked array, and the result array
print('Original 2D array:\n', array_2d)
print('Masked array (values < 20 are masked):\n', masked_array)
print('Result array after applying sin to unmasked elements:\n', result_array)

Original 2D array:
 [[78 56 30  5 20]
 [10 26 96 42 86]
 [49 12 87 12 37]
 [75 70 80 71 42]
 [14 71 78 69 61]]
Masked array (values < 20 are masked):
 [[78 56 30 -- 20]
 [-- 26 96 42 86]
 [49 -- 87 -- 37]
 [75 70 80 71 42]
 [-- 71 78 69 61]]
Result array after applying sin to unmasked elements:
 [[0.5139784559875352 -0.5215510020869119 -0.9880316240928618 --
  0.9129452507276277]
 [-- 0.7625584504796027 0.9835877454343449 -0.9165215479156338
  -0.9234584470040598]
 [-0.9537526527594719 -- -0.8218178366308225 -- -0.6435381333569995]
 [-0.38778163540943045 0.7738906815578891 -0.9938886539233752
  0.9510546532543747 -0.9165215479156338]
 [-- 0.9510546532543747 0.5139784559875352 -0.11478481378318722
  -0.9661177700083929]]


In [18]:
# Create a 2D NumPy array of shape (5, 5) with random integers
array_2d = np.random.randint(0, 100, size=(5, 5))

# Define a condition to mask elements less than 20
condition = array_2d < 20

# Create a masked array from the 2D array using the condition
masked_array = ma.masked_array(array_2d, mask=condition)

# Check if any masked elements are present
has_masked_elements = masked_array.mask.any()

# Print the original array, the masked array, and whether any masked elements are present
print('Original 2D array:\n', array_2d)
print('Masked array (values < 20 are masked):\n', masked_array)
print('Any masked elements present?:', has_masked_elements)

Original 2D array:
 [[88 10 66 36 98]
 [14 52  0 68 78]
 [64 94 29 97 18]
 [20 30 99 52 36]
 [68 65 11 30 81]]
Masked array (values < 20 are masked):
 [[88 -- 66 36 98]
 [-- 52 -- 68 78]
 [64 94 29 97 --]
 [20 30 99 52 36]
 [68 65 -- 30 81]]
Any masked elements present?: True
