In [1]:
import numpy as np

In [2]:
# Create a 2D NumPy array of random integers
array_2d = np.random.randint(0, 100, size=(5, 5))

# Specify the value for boolean indexing
threshold = 50

# Use boolean indexing to select elements greater than the threshold
selected_elements = array_2d[array_2d > threshold]

# Print the original array and the selected elements
print('Original 2D array:\n', array_2d)
print(f'\nElements greater than {threshold}:\n', selected_elements)

Original 2D array:
 [[58 99 88 98 67]
 [81 36 52 98 87]
 [63 57  1 72 43]
 [19 29 60 83 98]
 [84 61 46 44 88]]

Elements greater than 50:
 [58 99 88 98 67 81 52 98 87 63 57 72 60 83 98 84 61 88]


In [3]:
# Create a 1D NumPy array
array_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Define an index array to select specific elements
index_array = np.array([0, 2, 4, 6, 8])

# Use integer array indexing to select elements
selected_elements = array_1d[index_array]

# Print the original array and the selected elements
print('Original 1D array:\n', array_1d)
print('Index array:\n', index_array)
print('Selected elements:\n', selected_elements)

Original 1D array:
 [ 10  20  30  40  50  60  70  80  90 100]
Index array:
 [0 2 4 6 8]
Selected elements:
 [10 30 50 70 90]


In [4]:
# Create a 3D NumPy array of shape (3, 4, 5)
array_3d = np.random.randint(0, 100, size=(3, 4, 5))

# Define the row and column indices to select specific elements
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 3])

# Use fancy indexing to select elements from specific rows and columns
selected_elements = array_3d[row_indices[:, np.newaxis], col_indices]

# Print the original 3D array and the selected elements
print('Original 3D array:\n', array_3d)
print('Row indices:\n', row_indices)
print('Column indices:\n', col_indices)
print('Selected elements:\n', selected_elements)

Original 3D array:
 [[[80 32 37 94 90]
  [87 82 42  9 38]
  [40 35 62 72 96]
  [68 94 49 71 85]]

 [[80 87 47 19 59]
  [12 70 94 86 62]
  [19 92 26 26 23]
  [42 63 43 74 77]]

 [[54 59  3 43 26]
  [89 16 29 35 81]
  [26 91 83 37  6]
  [77 95 23 42 47]]]
Row indices:
 [0 1 2]
Column indices:
 [1 2 3]
Selected elements:
 [[[87 82 42  9 38]
  [40 35 62 72 96]
  [68 94 49 71 85]]

 [[12 70 94 86 62]
  [19 92 26 26 23]
  [42 63 43 74 77]]

 [[89 16 29 35 81]
  [26 91 83 37  6]
  [77 95 23 42 47]]]


In [5]:
# Create a 4D NumPy array of shape (3, 4, 5, 6) with random integers
array_4d = np.random.randint(0, 100, size=(3, 4, 5, 6))

# Use multi-dimensional indexing to select a subarray
# For example, select all elements from the first two blocks, 
# first three rows, first four columns, and first five depth slices
subarray = array_4d[:2, :3, :4, :5]

# Print the shape of the original 4D array and the selected subarray
print('Original 4D array shape:', array_4d.shape)
print('Selected subarray shape:', subarray.shape)
print('Selected subarray:\n', subarray)

Original 4D array shape: (3, 4, 5, 6)
Selected subarray shape: (2, 3, 4, 5)
Selected subarray:
 [[[[90 84 37 89  4]
   [53 23 54 77 23]
   [59 79 32 92 77]
   [59 67 60 86 92]]

  [[98 45 77 16  2]
   [ 9 41 71 24 91]
   [ 9 69  7 68 90]
   [76 75 88 39 28]]

  [[13 45 63 27 44]
   [26  1 14 35  2]
   [29 42 35 30 61]
   [ 9 98  2 81 57]]]


 [[[66 51 51 29 10]
   [26 36 87 53 45]
   [74  2 93 30 27]
   [86 41 53 65 85]]

  [[26 54 16 55  9]
   [63  5 42 60 22]
   [78 45 65 36 33]
   [93 66 17 50 89]]

  [[ 1  2  6 21 39]
   [78 83 89  2 46]
   [43 20 80  5 90]
   [12 93 50 21 73]]]]


In [6]:
# Create a 2D NumPy array of random floats between 0 and 1
array_2d = np.random.rand(5, 5)

# Define the conditions
condition1 = array_2d > 0.5
condition2 = array_2d < 0.8

# Use boolean indexing to select elements that satisfy both conditions
selected_elements = array_2d[condition1 & condition2]

# Print the original array and the selected elements
print('Original 2D array:\n', array_2d)
print('Elements greater than 0.5 and less than 0.8:\n', selected_elements)

Original 2D array:
 [[0.91602485 0.59843137 0.26280449 0.11673285 0.49123066]
 [0.57549623 0.13232003 0.61501489 0.71050658 0.08190488]
 [0.38600119 0.49581171 0.48929303 0.9058963  0.27795295]
 [0.31764742 0.87240137 0.69704223 0.69942109 0.04257376]
 [0.30034592 0.53305308 0.35934348 0.83867855 0.78956166]]
Elements greater than 0.5 and less than 0.8:
 [0.59843137 0.57549623 0.61501489 0.71050658 0.69704223 0.69942109
 0.53305308 0.78956166]
