In [1]:
import numpy as np

In [2]:
x =  np.array([[[ 1,  2,  3,  4],
               [ 5,  6,  7,  8],
               [ 9, 10, 11, 12]],

              [[13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]]])

y = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
x+y

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]],

       [[14, 16, 18, 20],
        [22, 24, 26, 28],
        [30, 32, 34, 36]]])

In [3]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
y = 3

x*y

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48]])

In [5]:
y =([2, 4, 6, 8])

x*y

array([[  2,   8,  18,  32],
       [ 10,  24,  42,  64],
       [ 18,  40,  66,  96],
       [ 26,  56,  90, 128]])

In [6]:
x = np.array([[[ 1,  2,  3,  4],
               [ 5,  6,  7,  8],
               [ 9, 10, 11, 12],
               [13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]],

              [[25, 26, 27, 28],
               [29, 30, 31, 32],
               [33, 34, 35, 36],
               [37, 38, 39, 40],
               [41, 42, 43, 44],
               [45, 46, 47, 48]]])

y = np.array([1, 2 ,3, 4, 5, 6])

x+y[:, np.newaxis]

array([[[ 2,  3,  4,  5],
        [ 7,  8,  9, 10],
        [12, 13, 14, 15],
        [17, 18, 19, 20],
        [22, 23, 24, 25],
        [27, 28, 29, 30]],

       [[26, 27, 28, 29],
        [31, 32, 33, 34],
        [36, 37, 38, 39],
        [41, 42, 43, 44],
        [46, 47, 48, 49],
        [51, 52, 53, 54]]])

In [14]:
# Initialize the array x of shape (2, 1, 3)
x = np.array([[[1, 2, 3]], 
              [[4, 5, 6]]])

# Initialize the array y of shape (1, 4, 1)
y = np.array([[[ 7], [ 8], [ 9], [10]]])

x+y

array([[[ 8,  9, 10],
        [ 9, 10, 11],
        [10, 11, 12],
        [11, 12, 13]],

       [[11, 12, 13],
        [12, 13, 14],
        [13, 14, 15],
        [14, 15, 16]]])

In [15]:
# Initialize the 3D array of shape (2, 3, 4)
x = np.array([[[10, 20, 30, 40],
               [50, 60, 70, 80],
               [90, 100, 110, 120]],

              [[130, 140, 150, 160],
               [170, 180, 190, 200],
               [210, 220, 230, 240]]])

# Initialize the 1D array of shape (4,)
y = np.array([1, 2, 3, 4])

x-y

array([[[  9,  18,  27,  36],
        [ 49,  58,  67,  76],
        [ 89,  98, 107, 116]],

       [[129, 138, 147, 156],
        [169, 178, 187, 196],
        [209, 218, 227, 236]]])

In [17]:
# Create a 2D array x of shape (5, 5)
x = np.array([[10, 20, 30, 40, 50],
              [5, 15, 25, 35, 45],
              [1, 2, 3, 4, 5],
              [6, 12, 18, 24, 30],
              [9, 18, 27, 36, 45]])

# Create a 1D array y of shape (5,)
y = np.array([1, 2, 3, 4, 5])

# Divide each row of x by the array y using broadcasting
result = x / y[:, np.newaxis]

print(result)

[[10.         20.         30.         40.         50.        ]
 [ 2.5         7.5        12.5        17.5        22.5       ]
 [ 0.33333333  0.66666667  1.          1.33333333  1.66666667]
 [ 1.5         3.          4.5         6.          7.5       ]
 [ 1.8         3.6         5.4         7.2         9.        ]]


In [18]:
# Create 1D array a of shape (8,)
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Create 1D array b of shape (4,)
b = np.array([10, 20, 30, 40])

# Reshape array a to (8, 1) to enable broadcasting
a_reshaped = a[:, np.newaxis]

# Perform element-wise addition using broadcasting
result = a_reshaped + b

print(result)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]
 [14 24 34 44]
 [15 25 35 45]
 [16 26 36 46]
 [17 27 37 47]
 [18 28 38 48]]


In [19]:
# Create a 3D array x of shape (3, 1, 5)
x = np.array([[[1, 2, 3, 4, 5]],
              [[6, 7, 8, 9, 10]],
              [[11, 12, 13, 14, 15]]])

# Create a 2D array y of shape (3, 5)
y = np.array([[10, 20, 30, 40, 50],
              [15, 25, 35, 45, 55],
              [20, 30, 40, 50, 60]])

# Add x and y using broadcasting
result = x + y[:, np.newaxis, :]

print(result)

[[[11 22 33 44 55]]

 [[21 32 43 54 65]]

 [[31 42 53 64 75]]]


In [20]:
# Create a 2D array x of shape (7, 3)
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12],
              [13, 14, 15],
              [16, 17, 18],
              [19, 20, 21]])

# Create a 1D array y of shape (7,)
y = np.array([1, 2, 3, 4, 5, 6, 7])

# Multiply each column of x by the array y using broadcasting
result = x * y[:, np.newaxis]

print(result)

[[  1   2   3]
 [  8  10  12]
 [ 21  24  27]
 [ 40  44  48]
 [ 65  70  75]
 [ 96 102 108]
 [133 140 147]]
