In [1]:
import numpy as np

In [3]:
# Define a custom ufunc that adds 10 to each element
def add_ten(x):
    return x + 10

# Create a ufunc from the custom function using np.frompyfunc
add_ten_ufunc = np.frompyfunc(add_ten, 1, 1)

# Create a 1D NumPy array of integers
array_1d = np.array([1, 2, 3, 4, 5])

# Apply the custom ufunc to the 1D array
result_array = add_ten_ufunc(array_1d)

# Print the original array and the resulting array
print('Original !D array:', array_1d)
print('Resulting array after applying add_ten_ufunc:', result_array)

Original !D array: [1 2 3 4 5]
Resulting array after applying add_ten_ufunc: [11 12 13 14 15]


In [4]:
# Create a 2D NumPy array of shape (3, 3) with random integers
array_2d = np.random.randint(1, 100, size=(3, 3))

# Use the np.sqrt ufunc to compute the square root of each element in the array
sqrt_array = np.sqrt(array_2d)

# Print the original array and the resulting array
print('Original 2D array:\n', array_2d)
print('Square root of each element:\n', sqrt_array)

Original 2D array:
 [[39 83 47]
 [55 40 95]
 [53  6 43]]
Square root of each element:
 [[6.244998   9.11043358 6.8556546 ]
 [7.41619849 6.32455532 9.74679434]
 [7.28010989 2.44948974 6.55743852]]


In [5]:
# Create a 2D NumPy array of shape (3, 3) with random integers
array_2d = np.random.randint(0, 10, size=(3, 3))

# Create a 1D NumPy array with random integers
array_1d = np.random.randint(0, 10, size=3)

# Use the np.add ufunc to add the 1D array to each row of the 2d array
result_array = np.add(array_2d, array_1d)

# Print the original arrays and the resulting array
print('Original 2D array:\n', array_2d)
print('1D array:\n', array_1d)
print('Resulting array after adding 1D array to each row of 2D array:\n', result_array)

Original 2D array:
 [[1 8 8]
 [3 0 0]
 [3 5 1]]
1D array:
 [5 2 7]
Resulting array after adding 1D array to each row of 2D array:
 [[ 6 10 15]
 [ 8  2  7]
 [ 8  7  8]]


In [6]:
# Create two 2D NumPy arrays of the same shape (3,3) with random integers
array_2d_1 = np.random.randint(0, 10, size=(3, 3))
array_2d_2 = np.random.randint(0, 10, size=(3, 3))

# Use the np.multiply ufunc to perform element-wise multiplication
result_array = np.multiply(array_2d_1, array_2d_2)

# Print the original arrays and the resulting array
print('Original 2D array 1:\n', array_2d_1)
print('Original 2D array 2:\n', array_2d_2)
print('Resulting array after element-wise multiplication:\n', result_array)

Original 2D array 1:
 [[9 2 2]
 [8 8 3]
 [8 7 7]]
Original 2D array 2:
 [[4 2 4]
 [3 4 2]
 [6 1 2]]
Resulting array after element-wise multiplication:
 [[36  4  8]
 [24 32  6]
 [48  7 14]]


In [7]:
# Create a 1D NumPy array of angles in radians
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

# Apply np.sin ufunc to the angles array
sin_values = np.sin(angles)

# Apply np.cos ufunc to the angles array
cos_values = np.cos(angles)

# Apply np.tan ufunc to the angles array
tan_values = np.tan(angles)

# Print the original angles array and the resulting arrays
print('Original angles (radians):\n', angles)
print('Sine values:\n', sin_values)
print('Cosine values:\n', cos_values)
print('Tangent values:\n', tan_values)

Original angles (radians):
 [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine values:
 [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values:
 [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent values:
 [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [8]:
# Create three 1D NumPy arrays
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([10, 20, 30, 40, 50])
condition_array = np.array([True, False, True, False, True])

# Use np.where ufunc to create a new array based on the condition
result_array = np.where(condition_array, array_1, array_2)

# Print the original arrays and the resulting array
print('Array 1:\n', array_1)
print('Array 2:\n', array_2)
print('Condition array:\n', condition_array)
print('Resulting array using np.where:\n', result_array)

Array 1:
 [1 2 3 4 5]
Array 2:
 [10 20 30 40 50]
Condition array:
 [ True False  True False  True]
Resulting array using np.where:
 [ 1 20  3 40  5]
