In [1]:
import numpy as np

In [2]:
np.add(4.0, 1.2)

5.2

In [3]:
np.subtract(4.0, 1.2)

2.8

In [4]:
np.multiply(4.0, 1.2)

4.8

In [5]:
np.divide(1.0, 4.0)

0.25

In [6]:
# Calculating the natural logarithm of 1e-50 and 2.5e-50
l1 = np.log(1e-50)
l2 = np.log(2.5e-50)

# Displaying the logarithm of the sum of exponentiations
print("Logarithm of the sum of exponentiations:")
print(np.logaddexp(l1, l2))

# Displaying the logarithm of the sum of exponentiations of the inputs in base-2
print("Logarithm of the sum of exponentiations of the inputs in base-2:")
print(np.logaddexp2(l1, l2)) 

Logarithm of the sum of exponentiations:
-113.87649168120691
Logarithm of the sum of exponentiations of the inputs in base-2:
-113.59955522772194


In [7]:
# Creating an array from 0 to 9
x = np.arange(10)

# Displaying the original array
print("Original array:")
print(x)

# Performing element-wise division of the array by 3 using true_divide function
print("Division of the array inputs, element-wise:")
print(np.true_divide(x, 3)) 

Original array:
[0 1 2 3 4 5 6 7 8 9]
Division of the array inputs, element-wise:
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [8]:
x = [1., 2., 3., 4.]
print("Original array:")
print(x)
print("Largest integer smaller or equal to the division of the inputs:")
print(np.floor_divide(x, 1.5))

Original array:
[1.0, 2.0, 3.0, 4.0]
Largest integer smaller or equal to the division of the inputs:
[0. 1. 2. 2.]


In [9]:
# Creating an array from 0 to 6
x = np.arange(7)

# Displaying the original array
print("Original array:")
print(x)

# Raising the elements of the array to the power of 3 and displaying the result
print("First array elements raised to powers from second array, element-wise:")
print(np.power(x, 3))

Original array:
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]


In [10]:
# Creating an array from 0 to 6
x = np.arange(7)

# Displaying the original array
print("Original array:")
print(x)

# Computing the element-wise remainder of division by 5 and displaying the result
print("Element-wise remainder of division:")
print(np.remainder(x, 5)) 

Original array:
[0 1 2 3 4 5 6]
Element-wise remainder of division:
[0 1 2 3 4 0 1]


In [11]:
# Creating an array with floating-point numbers
x = np.array([-10.2, 122.2, .20])

# Displaying the original array
print("Original array:")
print(x)

# Calculating the element-wise absolute value and displaying the result
print("Element-wise absolute value:")
print(np.absolute(x))

Original array:
[-10.2 122.2   0.2]
Element-wise absolute value:
[ 10.2 122.2   0.2]


In [12]:
# Rounding the numbers to the nearest integer
x = np.round([1.45, 1.50, 1.55])
print(x)

# Rounding the numbers to one decimal place
x = np.round([0.28, .50, .64], decimals=1)
print(x)

# Rounding the numbers to the nearest even value
x = np.round([.5, 1.5, 2.5, 3.5, 4.5])
print(x) 

[1. 2. 2.]
[0.3 0.5 0.6]
[0. 2. 2. 4. 4.]


In [13]:
# Creating an array with float values
x = np.array([-.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.0])

# Displaying the original array
print("Original array:")
print(x)

# Rounding elements of the array to the nearest integer
x = np.rint(x)
print("Round elements of the array to the nearest integer:")
print(x) 

Original array:
[-0.7 -1.5 -1.7  0.3  1.5  1.8  2. ]
Round elements of the array to the nearest integer:
[-1. -2. -2.  0.  2.  2.  2.]


In [14]:
# Creating an array with float values
x = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])

# Displaying the original array
print("Original array:")
print(x)

# Floor values of the array elements (round down to the nearest integer)
print("Floor values of the above array elements:")
print(np.floor(x))

# Ceil values of the array elements (round up to the nearest integer)
print("Ceil values of the above array elements:")
print(np.ceil(x))

# Truncated values of the array elements (remove decimal part without rounding)
print("Truncated values of the above array elements:")
print(np.trunc(x)) 

Original array:
[-1.6 -1.5 -0.3  0.1  1.4  1.8  2. ]
Floor values of the above array elements:
[-2. -2. -1.  0.  1.  1.  2.]
Ceil values of the above array elements:
[-1. -1. -0.  1.  2.  2.  2.]
Truncated values of the above array elements:
[-1. -1. -0.  0.  1.  1.  2.]
