In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create a Pandas Series
series = pd.Series([10, 20, 30, 40, 50])
print("Original Pandas Series:",series)
print("Type:",type(series))
# Convert the Pandas Series to a NumPy array
array = series.to_numpy()
print("\nPandas Series to a NumPy array:")
# Print the NumPy array
print(array)
print("Type:",type(array))

Original Pandas Series: 0    10
1    20
2    30
3    40
4    50
dtype: int64
Type: <class 'pandas.core.series.Series'>

Pandas Series to a NumPy array:
[10 20 30 40 50]
Type: <class 'numpy.ndarray'>


In [3]:
# Create a NumPy array
array = np.array([10, 20, 30, 40, 50])
print("Original NumPy array:",array)
print("Type:",type(array))
# Convert the NumPy array to a Pandas Series
series = pd.Series(array)
print("\nNumPy array to a Pandas Series:")
# Print the Pandas Series
print(series)
print("Type:",type(series))

Original NumPy array: [10 20 30 40 50]
Type: <class 'numpy.ndarray'>

NumPy array to a Pandas Series:
0    10
1    20
2    30
3    40
4    50
dtype: int32
Type: <class 'pandas.core.series.Series'>


In [4]:
# Create a Pandas DataFrame
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data)

# Print the original DataFrame
print("Original DataFrame:")
print(df)
print("Type:",type(df))


# Convert the DataFrame to a NumPy array
array = df.to_numpy()


# Print the NumPy array
print("\nNumPy Array:")
print(array)
print("Type:",type(array))


# Convert the NumPy array back to a DataFrame
df_back = pd.DataFrame(array, columns=df.columns)

# Print the DataFrame converted back from the NumPy array
print("\nDataFrame from NumPy Array:")
print(df_back)
print("Type:",type(df_back))

Original DataFrame:
   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12
Type: <class 'pandas.core.frame.DataFrame'>

NumPy Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Type: <class 'numpy.ndarray'>

DataFrame from NumPy Array:
   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12
Type: <class 'pandas.core.frame.DataFrame'>


In [5]:
# Create a NumPy array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Save the NumPy array to a CSV file
np.savetxt('array.csv', array, delimiter=',')

# Read the CSV file to verify contents
verified_array = np.loadtxt('array.csv', delimiter=',')

# Print the original NumPy array
print("Original NumPy Array:")
print(array)
print(type(array))
# Print the verified NumPy array read from the CSV file
print("\nVerified NumPy Array from CSV File:")
print(verified_array)
print(type(verified_array))

Original NumPy Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>

Verified NumPy Array from CSV File:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<class 'numpy.ndarray'>


In [6]:
# Read a CSV file into a NumPy array
# Ensure the 'array.csv' file exists in the working directory
array = np.loadtxt('array.csv', delimiter=',')

# Print the NumPy array
print(array)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
