In [1]:
import pandas as pd
import numpy as np

In [2]:
array = np.array([10, 5, 8, 20, 3])


In [3]:
np.max(array)

20

In [4]:
np.min(array)

3

In [5]:
# Create a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

array_2d = array_1d.reshape(2,4)
array_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
portion = array[2:]
portion

array([ 8, 20,  3])

In [8]:
# Create two NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

result_array = np.vstack((array1, array2))
result_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
# Create two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, -10],
                    [11, 12]])

# Perform matrix multiplication using numpy.dot()
result_matrix = np.dot(matrix1, matrix2)

# Alternatively, you can use the @ operator
# result_matrix = matrix1 @ matrix2

# Display the result
print(result_matrix)


[[ 58  24]
 [139  54]]


In [11]:
nums = np.array([1, 2, 3, -4, 5])
cumulative_sum = np.cumsum(nums)
cumulative_sum

array([1, 3, 6, 2, 7], dtype=int32)

In [12]:
random_array = np.random.rand(10)
unique_values = np.unique(random_array)
display(random_array)
display(unique_values)

array([0.52946524, 0.78920021, 0.17478068, 0.50895536, 0.37459876,
       0.03812518, 0.14328234, 0.8200023 , 0.59523938, 0.08854463])

array([0.03812518, 0.08854463, 0.14328234, 0.17478068, 0.37459876,
       0.50895536, 0.52946524, 0.59523938, 0.78920021, 0.8200023 ])

In [13]:
# Create a sample DataFrame
data = {'Name': ['Imen', 'Karthika', 'Cosimo', 'Cathrine'],
        'Age': [25, 30, 22, 35],
        'Salary': [50000, 60000, 45000, 70000]}

df = pd.DataFrame(data)

# Sort the DataFrame by the 'Salary' column in ascending order
sorted_df = df.sort_values(by='Salary')

# Display the sorted DataFrame
print(sorted_df)

       Name  Age  Salary
2    Cosimo   22   45000
0      Imen   25   50000
1  Karthika   30   60000
3  Cathrine   35   70000


In [14]:
# Create a sample DataFrame
data = {'Name': ['Imen', 'Karthika', 'Cosimo', 'Cathrine'],
        'Age': [25, 30, 22, 35],
        'Salary': [50000, 60000, 45000, 70000]}

df = pd.DataFrame(data)

# Define a custom function
def double_salary(salary):
    return salary * 2

# Apply the custom function to the 'Salary' column
df['Double_Salary'] = df['Salary'].apply(double_salary)

# Display the DataFrame with the new column
print(df)

       Name  Age  Salary  Double_Salary
0      Imen   25   50000         100000
1  Karthika   30   60000         120000
2    Cosimo   22   45000          90000
3  Cathrine   35   70000         140000


In [15]:
data = {'Name': ['Imen', 'Karthika', 'Cosimo', 'Cathrine'],
        'Age': [25, 30, 22, 35],
        'Salary': [50000, 60000, 45000, 70000]}

df = pd.DataFrame(data)

# Rename columns
df.rename(columns={'Name': 'Full_Name', 'Age': 'Years', 'Salary': 'Income'}, inplace=True)

# Display the DataFrame with renamed columns
print(df)

  Full_Name  Years  Income
0      Imen     25   50000
1  Karthika     30   60000
2    Cosimo     22   45000
3  Cathrine     35   70000
