In [1]:
import numpy as np

In [2]:
#Q8
# Write a NumPy program to sort the specified number of elements from beginning of a given array.
nums = np.random.rand(10)
nums

array([0.09573225, 0.88796374, 0.37569566, 0.22547025, 0.42774748,
       0.30934126, 0.7394924 , 0.82310717, 0.24689302, 0.4105967 ])

In [3]:
nums[np.argpartition(nums, range(5))]

array([0.09573225, 0.22547025, 0.24689302, 0.30934126, 0.37569566,
       0.88796374, 0.7394924 , 0.82310717, 0.42774748, 0.4105967 ])

In [4]:
#Q9
nums = np.random.randint(0,10, (3,3))
nums

array([[5, 3, 2],
       [9, 7, 7],
       [7, 4, 9]])

In [5]:
nums[nums[:, 1].argsort()]

array([[5, 3, 2],
       [7, 4, 9],
       [9, 7, 7]])