In [1]:
import numpy as np

In [2]:
# Creating NumPy arrays for student IDs and their heights
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])

# Sorting the indices based on 'student_id' and then 'student_height'
indices = np.lexsort((student_id, student_height))

# Displaying the sorted indices
print("Sorted indices:")
print(indices)

# Displaying the sorted data based on the obtained indices
print("Sorted data:")
for n in indices:
    print(student_id[n], student_height[n]) 

Sorted indices:
[4 0 5 3 6 1 2]
Sorted data:
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


In [3]:
# Creating a NumPy array for student IDs
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

# Displaying the original array
print("Original array:")
print(student_id)

# Sorting the indices of the array's elements in ascending order
i = np.argsort(student_id)

# Displaying the indices of the sorted elements
print("Indices of the sorted elements of a given array:")
print(i) 

Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]
